/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AuStakeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admins"
      | "burn"
      | "createOperation"
      | "getOperation"
      | "idToOperation"
      | "lockPeriod"
      | "operationStakes"
      | "owner"
      | "projectWallet"
      | "providerToOperationIds"
      | "renounceOwnership"
      | "setAdmin"
      | "setLockPeriod"
      | "setOperationReward"
      | "setProjectWallet"
      | "stake"
      | "stakes"
      | "tokenToOperationIds"
      | "tokenTvl"
      | "transferOwnership"
      | "triggerReward"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminStatusChanged"
      | "OperationCreated"
      | "OwnershipTransferred"
      | "RewardPaid"
      | "Staked"
      | "Unstaked"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createOperation",
    values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOperation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "idToOperation",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lockPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "operationStakes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "projectWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "providerToOperationIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperationReward",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProjectWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenToOperationIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenTvl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerReward",
    values: [AddressLike, BytesLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "idToOperation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockPeriod", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operationStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "projectWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "providerToOperationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLockPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperationReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProjectWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenToOperationIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenTvl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerReward",
    data: BytesLike
  ): Result;
}

export namespace AdminStatusChangedEvent {
  export type InputTuple = [admin: AddressLike, status: boolean];
  export type OutputTuple = [admin: string, status: boolean];
  export interface OutputObject {
    admin: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperationCreatedEvent {
  export type InputTuple = [
    operationId: BytesLike,
    name: string,
    token: AddressLike
  ];
  export type OutputTuple = [operationId: string, name: string, token: string];
  export interface OutputObject {
    operationId: string;
    name: string;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPaidEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    operationId: BytesLike
  ];
  export type OutputTuple = [user: string, amount: bigint, operationId: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    token: AddressLike,
    user: AddressLike,
    amount: BigNumberish,
    operationId: BytesLike
  ];
  export type OutputTuple = [
    token: string,
    user: string,
    amount: bigint,
    operationId: string
  ];
  export interface OutputObject {
    token: string;
    user: string;
    amount: bigint;
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    token: AddressLike,
    user: AddressLike,
    amount: BigNumberish,
    operationId: BytesLike
  ];
  export type OutputTuple = [
    token: string,
    user: string,
    amount: bigint,
    operationId: string
  ];
  export interface OutputObject {
    token: string;
    user: string;
    amount: bigint;
    operationId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuStake extends BaseContract {
  connect(runner?: ContractRunner | null): AuStake;
  waitForDeployment(): Promise<this>;

  interface: AuStakeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  burn: TypedContractMethod<
    [token: AddressLike, user: AddressLike, operationId: BytesLike],
    [void],
    "nonpayable"
  >;

  createOperation: TypedContractMethod<
    [
      name: string,
      token: AddressLike,
      provider: AddressLike,
      lengthInDays: BigNumberish,
      reward: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getOperation: TypedContractMethod<
    [id: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        token: string;
        provider: string;
        lengthInDays: bigint;
        reward: bigint;
        tokenTvl: bigint;
      }
    ],
    "view"
  >;

  idToOperation: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        token: string;
        provider: string;
        lengthInDays: bigint;
        reward: bigint;
        tokenTvl: bigint;
      }
    ],
    "view"
  >;

  lockPeriod: TypedContractMethod<[], [bigint], "view">;

  operationStakes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  projectWallet: TypedContractMethod<[], [string], "view">;

  providerToOperationIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAdmin: TypedContractMethod<
    [user: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setLockPeriod: TypedContractMethod<
    [_lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  setOperationReward: TypedContractMethod<
    [id: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProjectWallet: TypedContractMethod<
    [_projectWallet: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [token: AddressLike, operationId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  tokenToOperationIds: TypedContractMethod<
    [arg0: AddressLike],
    [string],
    "view"
  >;

  tokenTvl: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerReward: TypedContractMethod<
    [token: AddressLike, operationId: BytesLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [token: AddressLike, user: AddressLike, operationId: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createOperation"
  ): TypedContractMethod<
    [
      name: string,
      token: AddressLike,
      provider: AddressLike,
      lengthInDays: BigNumberish,
      reward: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getOperation"
  ): TypedContractMethod<
    [id: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        token: string;
        provider: string;
        lengthInDays: bigint;
        reward: bigint;
        tokenTvl: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "idToOperation"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint] & {
        name: string;
        token: string;
        provider: string;
        lengthInDays: bigint;
        reward: bigint;
        tokenTvl: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "lockPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operationStakes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "projectWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "providerToOperationIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAdmin"
  ): TypedContractMethod<
    [user: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLockPeriod"
  ): TypedContractMethod<[_lockPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperationReward"
  ): TypedContractMethod<
    [id: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setProjectWallet"
  ): TypedContractMethod<[_projectWallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [token: AddressLike, operationId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tokenToOperationIds"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "tokenTvl"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerReward"
  ): TypedContractMethod<
    [token: AddressLike, operationId: BytesLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AdminStatusChanged"
  ): TypedContractEvent<
    AdminStatusChangedEvent.InputTuple,
    AdminStatusChangedEvent.OutputTuple,
    AdminStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "OperationCreated"
  ): TypedContractEvent<
    OperationCreatedEvent.InputTuple,
    OperationCreatedEvent.OutputTuple,
    OperationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardPaid"
  ): TypedContractEvent<
    RewardPaidEvent.InputTuple,
    RewardPaidEvent.OutputTuple,
    RewardPaidEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;

  filters: {
    "AdminStatusChanged(address,bool)": TypedContractEvent<
      AdminStatusChangedEvent.InputTuple,
      AdminStatusChangedEvent.OutputTuple,
      AdminStatusChangedEvent.OutputObject
    >;
    AdminStatusChanged: TypedContractEvent<
      AdminStatusChangedEvent.InputTuple,
      AdminStatusChangedEvent.OutputTuple,
      AdminStatusChangedEvent.OutputObject
    >;

    "OperationCreated(bytes32,string,address)": TypedContractEvent<
      OperationCreatedEvent.InputTuple,
      OperationCreatedEvent.OutputTuple,
      OperationCreatedEvent.OutputObject
    >;
    OperationCreated: TypedContractEvent<
      OperationCreatedEvent.InputTuple,
      OperationCreatedEvent.OutputTuple,
      OperationCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardPaid(address,uint256,bytes32)": TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;
    RewardPaid: TypedContractEvent<
      RewardPaidEvent.InputTuple,
      RewardPaidEvent.OutputTuple,
      RewardPaidEvent.OutputObject
    >;

    "Staked(address,address,uint256,bytes32)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,address,uint256,bytes32)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
  };
}
