/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auSysSol from './AuSys.sol';
export type { auSysSol };
import type * as aurumSol from './Aurum.sol';
export type { aurumSol };
export type { AuStake } from './AuStake';
export type { Aura } from './Aura';
export type { AuraGoat } from './AuraGoat';
export type { AuraGoatRed } from './AuraGoatRed';
