/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auraGoat20Sol from './AuraGoat20.sol';
export type { auraGoat20Sol };
export type { AuStake } from './AuStake';
