/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface AurumNodeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addItem"
      | "nodeHandOn"
      | "nodeHandoff"
      | "nodeSign"
      | "owner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addItem",
    values: [
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeHandOn",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeHandoff",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BytesLike,
      BigNumberish[],
      AddressLike,
      BigNumberish[],
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeSign",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodeHandOn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nodeHandoff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodeSign", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
}

export interface AurumNode extends BaseContract {
  connect(runner?: ContractRunner | null): AurumNode;
  waitForDeployment(): Promise<this>;

  interface: AurumNodeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addItem: TypedContractMethod<
    [
      itemOwner: AddressLike,
      id: BytesLike,
      weight: BigNumberish,
      amount: BigNumberish,
      item: AddressLike,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nodeHandOn: TypedContractMethod<
    [driver: AddressLike, reciever: AddressLike, id: BytesLike],
    [void],
    "nonpayable"
  >;

  nodeHandoff: TypedContractMethod<
    [
      node: AddressLike,
      driver: AddressLike,
      reciever: AddressLike,
      id: BytesLike,
      tokenIds: BigNumberish[],
      token: AddressLike,
      quantities: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  nodeSign: TypedContractMethod<
    [node: AddressLike, driver: AddressLike, jobid: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addItem"
  ): TypedContractMethod<
    [
      itemOwner: AddressLike,
      id: BytesLike,
      weight: BigNumberish,
      amount: BigNumberish,
      item: AddressLike,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nodeHandOn"
  ): TypedContractMethod<
    [driver: AddressLike, reciever: AddressLike, id: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nodeHandoff"
  ): TypedContractMethod<
    [
      node: AddressLike,
      driver: AddressLike,
      reciever: AddressLike,
      id: BytesLike,
      tokenIds: BigNumberish[],
      token: AddressLike,
      quantities: BigNumberish[],
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nodeSign"
  ): TypedContractMethod<
    [node: AddressLike, driver: AddressLike, jobid: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
