/**
 * Diamond P2P Service - Handles P2P trading operations via Diamond's AuSysFacet
 *
 * Provides methods for creating, accepting, and canceling P2P offers.
 */

import { ethers } from 'ethers';
import { DiamondContext } from './diamond-context';
import {
  P2POffer,
  P2POfferStatus,
  CreateP2POfferInput,
  IP2PService,
  IP2PRepository,
  mapContractStatusToP2PStatus,
} from '@/domain/p2p';
import {
  NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS,
  NEXT_PUBLIC_DIAMOND_ADDRESS,
} from '@/chain-constants';

const ERC20_ABI = [
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
];

/**
 * Diamond-based implementation of P2P Service (write operations)
 */
export class DiamondP2PService implements IP2PService {
  private context: DiamondContext;

  constructor(context: DiamondContext) {
    this.context = context;
  }

  /**
   * Create a new P2P offer
   * @param input The offer details
   * @returns The created offer ID (bytes32)
   */
  async createOffer(input: CreateP2POfferInput): Promise<string> {
    const diamond = this.context.getDiamond();
    const signerAddress = await this.context.getSignerAddress();

    console.log('[DiamondP2PService] Creating P2P offer:', {
      token: input.token,
      tokenId: input.tokenId,
      quantity: input.quantity.toString(),
      price: input.price.toString(),
      isSellOffer: input.isSellOffer,
      targetCounterparty: input.targetCounterparty || 'open',
    });

    // Build the AuSysOrder struct for createAuSysOrder
    // For P2P: one party is the creator, the other is address(0) or targetCounterparty
    const order = {
      id: ethers.ZeroHash, // Will be generated by contract
      token: input.token,
      tokenId: input.tokenId,
      tokenQuantity: input.quantity,
      price: input.price,
      txFee: 0n, // Will be calculated by contract
      buyer: input.isSellOffer
        ? input.targetCounterparty || ethers.ZeroAddress
        : signerAddress,
      seller: input.isSellOffer
        ? signerAddress
        : input.targetCounterparty || ethers.ZeroAddress,
      journeyIds: [],
      nodes: input.nodes || [],
      locationData: {
        startLocation: { lat: '', lng: '' },
        endLocation: { lat: '', lng: '' },
        startName: '',
        endName: '',
      },
      currentStatus: 0,
      contractualAgreement: ethers.ZeroHash,
      // P2P fields
      isSellerInitiated: input.isSellOffer,
      targetCounterparty: input.targetCounterparty || ethers.ZeroAddress,
      expiresAt: input.expiresAt || 0,
    };

    try {
      const tx = await diamond.createAuSysOrder(order);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Transaction confirmed:', receipt.hash);

      // Extract order ID from P2POfferCreated or AuSysOrderCreated event
      const p2pEvent = receipt.logs.find((log: ethers.Log) => {
        try {
          const parsed = diamond.interface.parseLog({
            topics: log.topics as string[],
            data: log.data,
          });
          return (
            parsed?.name === 'P2POfferCreated' ||
            parsed?.name === 'AuSysOrderCreated'
          );
        } catch {
          return false;
        }
      });

      if (p2pEvent) {
        const parsed = diamond.interface.parseLog({
          topics: p2pEvent.topics as string[],
          data: p2pEvent.data,
        });
        const orderId = parsed?.args?.[0] || parsed?.args?.orderId;
        console.log('[DiamondP2PService] Created offer ID:', orderId);
        return orderId;
      }

      throw new Error('Could not find order ID in transaction receipt');
    } catch (error) {
      console.error('[DiamondP2PService] Error creating offer:', error);
      throw error;
    }
  }

  /**
   * Accept a P2P offer
   *
   * When accepting a sell offer, the acceptor is the buyer and must pay ERC20.
   * This method automatically checks the buyer's ERC20 allowance for the
   * Diamond contract and requests approval if insufficient.
   *
   * @param offerId The offer to accept
   */
  async acceptOffer(offerId: string): Promise<void> {
    const diamond = this.context.getDiamond();

    console.log('[DiamondP2PService] Accepting P2P offer:', offerId);

    try {
      // Fetch the offer to determine if we need ERC20 approval
      const order = await diamond.getAuSysOrder(offerId);

      // If this is a sell offer, the acceptor is the buyer → needs ERC20 approval
      if (order.isSellerInitiated) {
        const totalCost =
          BigInt(order.price.toString()) *
            BigInt(order.tokenQuantity.toString()) +
          BigInt(order.txFee.toString());

        await this.ensureQuoteTokenApproval(totalCost);
      }

      const tx = await diamond.acceptP2POffer(offerId);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Offer accepted:', receipt.hash);
    } catch (error) {
      console.error('[DiamondP2PService] Error accepting offer:', error);
      throw error;
    }
  }

  /**
   * Ensure the quote token (ERC20) has sufficient allowance for the Diamond contract.
   * If not, request an unlimited approval to avoid repeated approvals.
   */
  private async ensureQuoteTokenApproval(amount: bigint): Promise<void> {
    const signer = this.context.getSigner();
    const signerAddress = await this.context.getSignerAddress();

    // Use context helper if available (for testability), else create contract
    const quoteToken =
      'getQuoteTokenContract' in this.context
        ? (this.context as any).getQuoteTokenContract()
        : new ethers.Contract(
            NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS,
            ERC20_ABI,
            signer,
          );

    console.log('[DiamondP2PService] Checking quote token allowance...', {
      signerAddress,
      diamondAddress: NEXT_PUBLIC_DIAMOND_ADDRESS,
      requiredAmount: amount.toString(),
    });

    const currentAllowance = await quoteToken.allowance(
      signerAddress,
      NEXT_PUBLIC_DIAMOND_ADDRESS,
    );

    if (BigInt(currentAllowance.toString()) < amount) {
      console.log(
        '[DiamondP2PService] Insufficient allowance, approving unlimited amount...',
      );
      const tx = await quoteToken.approve(
        NEXT_PUBLIC_DIAMOND_ADDRESS,
        ethers.MaxUint256,
      );
      await tx.wait();
      console.log('[DiamondP2PService] Quote token approved.');
    } else {
      console.log(
        '[DiamondP2PService] Sufficient allowance, no approval needed.',
      );
    }
  }

  /**
   * Cancel a P2P offer (only creator can cancel)
   * @param offerId The offer to cancel
   */
  async cancelOffer(offerId: string): Promise<void> {
    const diamond = this.context.getDiamond();

    console.log('[DiamondP2PService] Canceling P2P offer:', offerId);

    try {
      const tx = await diamond.cancelP2POffer(offerId);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Offer canceled:', receipt.hash);
    } catch (error) {
      console.error('[DiamondP2PService] Error canceling offer:', error);
      throw error;
    }
  }
}

/**
 * Diamond-based implementation of P2P Repository (read operations)
 */
export class DiamondP2PRepository implements IP2PRepository {
  private context: DiamondContext;

  constructor(context: DiamondContext) {
    this.context = context;
  }

  /**
   * Get all open P2P offers
   */
  async getOpenOffers(): Promise<P2POffer[]> {
    const diamond = this.context.getDiamond();

    try {
      const offerIds: string[] = await diamond.getOpenP2POffers();
      console.log(
        '[DiamondP2PRepository] Found',
        offerIds.length,
        'open offers',
      );

      const offers = await Promise.all(offerIds.map((id) => this.getOffer(id)));

      return offers.filter((o): o is P2POffer => o !== null);
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting open offers:', error);
      return [];
    }
  }

  /**
   * Get P2P offers created by a specific user
   */
  async getUserOffers(userAddress: string): Promise<P2POffer[]> {
    const diamond = this.context.getDiamond();

    try {
      const offerIds: string[] = await diamond.getUserP2POffers(userAddress);
      console.log(
        '[DiamondP2PRepository] Found',
        offerIds.length,
        'offers for user',
        userAddress,
      );

      const offers = await Promise.all(offerIds.map((id) => this.getOffer(id)));

      return offers.filter((o): o is P2POffer => o !== null);
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting user offers:', error);
      return [];
    }
  }

  /**
   * Get a specific P2P offer by ID
   */
  async getOffer(offerId: string): Promise<P2POffer | null> {
    const diamond = this.context.getDiamond();

    try {
      const order = await diamond.getAuSysOrder(offerId);

      // Check if order exists (id will be zero hash if not found)
      if (order.id === ethers.ZeroHash) {
        return null;
      }

      const offer: P2POffer = {
        id: order.id,
        creator: order.isSellerInitiated ? order.seller : order.buyer,
        targetCounterparty:
          order.targetCounterparty === ethers.ZeroAddress
            ? null
            : order.targetCounterparty,
        token: order.token,
        tokenId: order.tokenId.toString(),
        quantity: BigInt(order.tokenQuantity.toString()),
        price: BigInt(order.price.toString()),
        txFee: BigInt(order.txFee.toString()),
        isSellerInitiated: order.isSellerInitiated,
        status: mapContractStatusToP2PStatus(Number(order.currentStatus)),
        buyer: order.buyer,
        seller: order.seller,
        createdAt: 0, // Not stored in contract, would need indexer
        expiresAt: Number(order.expiresAt),
        locationData: order.locationData,
        nodes: order.nodes || [],
      };

      return offer;
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting offer:', error);
      return null;
    }
  }

  /**
   * Get offers filtered by asset
   */
  async getOffersByAsset(token: string, tokenId: string): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter(
      (o) =>
        o.token.toLowerCase() === token.toLowerCase() && o.tokenId === tokenId,
    );
  }

  /**
   * Get buy offers (offers from buyers looking to purchase)
   */
  async getBuyOffers(): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter((o) => !o.isSellerInitiated);
  }

  /**
   * Get sell offers (offers from sellers looking to sell)
   */
  async getSellOffers(): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter((o) => o.isSellerInitiated);
  }
}
