/**
 * Diamond P2P Service - Handles P2P trading operations via Diamond's AuSysFacet
 *
 * Provides methods for creating, accepting, and canceling P2P offers.
 */

import { ethers } from 'ethers';
import { DiamondContext } from './diamond-context';
import {
  P2POffer,
  P2POfferStatus,
  CreateP2POfferInput,
  P2PDeliveryDetails,
  IP2PService,
  IP2PRepository,
  mapContractStatusToP2PStatus,
} from '@/domain/p2p';
import {
  NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS,
  NEXT_PUBLIC_DIAMOND_ADDRESS,
} from '@/chain-constants';

const ERC20_ABI = [
  'function approve(address spender, uint256 amount) external returns (bool)',
  'function allowance(address owner, address spender) external view returns (uint256)',
];

const ERC1155_ABI = [
  'function isApprovedForAll(address account, address operator) external view returns (bool)',
  'function setApprovalForAll(address operator, bool approved) external',
];

// ============================================================================
// P2P Custom Error Decoding
// ============================================================================

/** Map of AuSysFacet P2P error selectors to user-friendly messages */
const P2P_ERROR_MAP: Record<string, string> = {
  '0x6df5846d': 'Offer not found. It may have been removed.',
  '0x2b8b1d43':
    'This offer is no longer open. It may have already been accepted, cancelled, or expired.',
  '0x9cb13087': 'This offer has expired.',
  '0xcb6036a0': 'This offer is targeted to a different counterparty.',
  '0x520e449f': 'You cannot accept your own offer.',
  '0x6035cb58': 'Only the offer creator can cancel this offer.',
  '0xe6c4247b': 'Invalid address in the offer.',
  '0x2c5211c6': 'Invalid amount – price or quantity cannot be zero.',
  '0xb7f05f41': 'Payment token has not been configured on the contract.',
  '0xe237d922':
    'The Diamond contract needs approval to transfer your tokens. This should be requested automatically.',
  '0x03dee4c5':
    'Insufficient token balance. You do not have enough of this asset to create the offer.',
  '0x48f5c3ed':
    'You are not authorized to create the delivery journey. Only the buyer, seller, or admin can do this.',
};

/**
 * Decode a contract revert into a user-friendly message.
 * Falls back to the raw error message if the selector is unknown.
 */
export function decodeP2PError(error: unknown): string {
  if (error && typeof error === 'object') {
    const err = error as Record<string, unknown>;

    // ethers v6 CALL_EXCEPTION: data contains the error selector
    if (typeof err.data === 'string' && err.data.length >= 10) {
      const selector = err.data.slice(0, 10).toLowerCase();
      if (P2P_ERROR_MAP[selector]) return P2P_ERROR_MAP[selector];
    }

    // Some providers nest the data inside err.error
    if (err.error && typeof err.error === 'object') {
      const inner = err.error as Record<string, unknown>;
      if (typeof inner.data === 'string' && inner.data.length >= 10) {
        const selector = inner.data.slice(0, 10).toLowerCase();
        if (P2P_ERROR_MAP[selector]) return P2P_ERROR_MAP[selector];
      }
    }

    // ethers v6 already decoded the reason
    if (typeof err.reason === 'string') return err.reason;

    // Fall back to message
    if (typeof err.message === 'string') {
      // Try to extract the selector from the message body
      const match = err.message.match(/data="(0x[a-fA-F0-9]{8,})"/);
      if (match) {
        const selector = match[1].slice(0, 10).toLowerCase();
        if (P2P_ERROR_MAP[selector]) return P2P_ERROR_MAP[selector];
      }
      return err.message;
    }
  }
  return String(error);
}

/**
 * Diamond-based implementation of P2P Service (write operations)
 */
export class DiamondP2PService implements IP2PService {
  private context: DiamondContext;

  constructor(context: DiamondContext) {
    this.context = context;
  }

  /**
   * Create a new P2P offer
   * @param input The offer details
   * @returns The created offer ID (bytes32)
   */
  async createOffer(input: CreateP2POfferInput): Promise<string> {
    const diamond = this.context.getDiamond();
    const signerAddress = await this.context.getSignerAddress();

    console.log('[DiamondP2PService] Creating P2P offer:', {
      token: input.token,
      tokenId: input.tokenId,
      quantity: input.quantity.toString(),
      price: input.price.toString(),
      isSellOffer: input.isSellOffer,
      targetCounterparty: input.targetCounterparty || 'open',
    });

    // Build the AuSysOrder struct for createAuSysOrder
    // For P2P: one party is the creator, the other is address(0) or targetCounterparty
    const buyDestination = input.deliveryDestination;
    const order = {
      id: ethers.ZeroHash, // Will be generated by contract
      token: input.token,
      tokenId: input.tokenId,
      tokenQuantity: input.quantity,
      price: input.price,
      txFee: 0n, // Will be calculated by contract
      buyer: input.isSellOffer
        ? input.targetCounterparty || ethers.ZeroAddress
        : signerAddress,
      seller: input.isSellOffer
        ? signerAddress
        : input.targetCounterparty || ethers.ZeroAddress,
      journeyIds: [],
      nodes: input.nodes || [],
      locationData: {
        startLocation: { lat: '', lng: '' },
        endLocation:
          !input.isSellOffer && buyDestination
            ? {
                lat: buyDestination.lat,
                lng: buyDestination.lng,
              }
            : { lat: '', lng: '' },
        startName: '',
        endName:
          !input.isSellOffer && buyDestination ? buyDestination.address : '',
      },
      currentStatus: 0,
      contractualAgreement: ethers.ZeroHash,
      // P2P fields
      isSellerInitiated: input.isSellOffer,
      targetCounterparty: input.targetCounterparty || ethers.ZeroAddress,
      expiresAt: input.expiresAt || 0,
    };

    try {
      const payTokenAddress = await this.getConfiguredPayTokenAddress();

      if (input.isSellOffer) {
        // Sell offer: seller escrows ERC1155 tokens → needs ERC1155 approval
        console.log(
          '[DiamondP2PService] Sell offer — ensuring ERC1155 approval for',
          input.token,
        );
        await this.ensureERC1155Approval(input.token);
        console.log(
          '[DiamondP2PService] ERC1155 approval complete, proceeding to create order...',
        );
      } else {
        // Buy offer: buyer escrows ERC20 (price + txFee) → needs ERC20 approval
        // Contract calculates txFee = (price * 2) / 100
        const txFee = (input.price * BigInt(2)) / BigInt(100);
        const totalCost = input.price + txFee;
        console.log(
          '[DiamondP2PService] Buy offer — ensuring ERC20 approval for',
          totalCost.toString(),
        );
        await this.ensureQuoteTokenApproval(totalCost, payTokenAddress);
      }

      const tx = await diamond.createAuSysOrder(order);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Transaction confirmed:', receipt.hash);

      // Extract order ID from P2POfferCreated or AuSysOrderCreated event
      const p2pEvent = receipt.logs.find((log: ethers.Log) => {
        try {
          const parsed = diamond.interface.parseLog({
            topics: log.topics as string[],
            data: log.data,
          });
          return (
            parsed?.name === 'P2POfferCreated' ||
            parsed?.name === 'AuSysOrderCreated'
          );
        } catch {
          return false;
        }
      });

      if (p2pEvent) {
        const parsed = diamond.interface.parseLog({
          topics: p2pEvent.topics as string[],
          data: p2pEvent.data,
        });
        const orderId = parsed?.args?.[0] || parsed?.args?.orderId;
        console.log('[DiamondP2PService] Created offer ID:', orderId);
        return orderId;
      }

      throw new Error('Could not find order ID in transaction receipt');
    } catch (error) {
      console.error('[DiamondP2PService] Error creating offer:', error);
      const decoded = decodeP2PError(error);
      const wrapped = new Error(decoded);
      (wrapped as any).originalError = error;
      throw wrapped;
    }
  }

  /**
   * Accept a P2P offer
   *
   * When accepting a sell offer, the acceptor is the buyer and must pay ERC20.
   * This method automatically checks the buyer's ERC20 allowance for the
   * Diamond contract and requests approval if insufficient.
   *
   * @param offerId The offer to accept
   */
  async acceptOffer(offerId: string): Promise<void> {
    const diamond = this.context.getDiamond();

    console.log('[DiamondP2PService] Accepting P2P offer:', offerId);

    try {
      // Fetch the offer to determine approval needs
      const order = await diamond.getAuSysOrder(offerId);

      if (order.isSellerInitiated) {
        // Sell offer: acceptor is BUYER → needs ERC20 approval for price + txFee
        const payTokenAddress = await this.getConfiguredPayTokenAddress();
        const totalCost =
          BigInt(order.price.toString()) + BigInt(order.txFee.toString());
        console.log(
          '[DiamondP2PService] Accepting sell offer — ensuring ERC20 approval for',
          totalCost.toString(),
        );
        await this.ensureQuoteTokenApproval(totalCost, payTokenAddress);
      } else {
        // Buy offer: acceptor is SELLER → needs ERC1155 approval to escrow tokens
        console.log(
          '[DiamondP2PService] Accepting buy offer — ensuring ERC1155 approval for',
          order.token,
        );
        await this.ensureERC1155Approval(order.token);
      }

      const tx = await diamond.acceptP2POffer(offerId);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Offer accepted:', receipt.hash);
    } catch (error) {
      console.error('[DiamondP2PService] Error accepting offer:', error);
      // Re-throw with decoded message for the UI
      const decoded = decodeP2PError(error);
      const wrapped = new Error(decoded);
      (wrapped as any).originalError = error;
      throw wrapped;
    }
  }

  /**
   * Accept a P2P offer and immediately create a delivery journey.
   *
   * Sequence:
   * 1. Fetch offer details to determine ERC20 approval amount
   * 2. Ensure ERC20 approval covers price + txFee + bounty
   * 3. Call acceptP2POffer → wait for confirmation
   * 4. Call createOrderJourney → wait for confirmation
   *
   * If step 3 fails, step 4 is never attempted.
   *
   * @param offerId The offer to accept
   * @param delivery Delivery details for journey creation
   */
  async acceptOfferWithDelivery(
    offerId: string,
    delivery: P2PDeliveryDetails,
  ): Promise<void> {
    const diamond = this.context.getDiamond();

    console.log('[DiamondP2PService] acceptOfferWithDelivery:', offerId);

    try {
      // 1. Fetch offer to determine approval needs
      const order = await diamond.getAuSysOrder(offerId);

      // 2. Handle approvals based on offer type
      if (order.isSellerInitiated) {
        // Sell offer: acceptor is BUYER → ERC20 approval for price + txFee + bounty
        const payTokenAddress = await this.getConfiguredPayTokenAddress();
        const totalCost =
          BigInt(order.price.toString()) +
          BigInt(order.txFee.toString()) +
          delivery.bountyWei;
        console.log(
          '[DiamondP2PService] Accepting sell offer with delivery — ERC20 approval for',
          totalCost.toString(),
        );
        await this.ensureQuoteTokenApproval(totalCost, payTokenAddress);
      } else {
        // Buy offer: acceptor is SELLER → ERC1155 approval to escrow tokens
        console.log(
          '[DiamondP2PService] Accepting buy offer with delivery — ERC1155 approval for',
          order.token,
        );
        await this.ensureERC1155Approval(order.token);
      }

      // 3. Accept the offer
      const acceptTx = await diamond.acceptP2POffer(offerId);
      await acceptTx.wait();
      console.log('[DiamondP2PService] Offer accepted, creating journey...');

      // 4. Create the delivery journey
      const journeyTx = await diamond.createOrderJourney(
        offerId,
        delivery.senderNodeAddress,
        delivery.receiverAddress,
        delivery.parcelData,
        delivery.bountyWei,
        delivery.etaTimestamp,
        delivery.tokenQuantity,
        delivery.assetId,
      );
      await journeyTx.wait();
      console.log('[DiamondP2PService] Journey created successfully');
    } catch (error) {
      console.error(
        '[DiamondP2PService] acceptOfferWithDelivery error:',
        error,
      );
      const decoded = decodeP2PError(error);
      const wrapped = new Error(decoded);
      (wrapped as any).originalError = error;
      throw wrapped;
    }
  }

  /**
   * Ensure the quote token (ERC20) has sufficient allowance for the Diamond contract.
   * If not, request an unlimited approval to avoid repeated approvals.
   */
  private async ensureQuoteTokenApproval(
    amount: bigint,
    quoteTokenAddress: string,
  ): Promise<void> {
    const signer = this.context.getSigner();
    const signerAddress = await this.context.getSignerAddress();

    // Use context helper only for the default configured token (keeps tests simple).
    const shouldUseContextHelper =
      'getQuoteTokenContract' in this.context &&
      quoteTokenAddress.toLowerCase() ===
        NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS.toLowerCase();
    const quoteToken = shouldUseContextHelper
      ? (this.context as any).getQuoteTokenContract()
      : new ethers.Contract(quoteTokenAddress, ERC20_ABI, signer);

    console.log('[DiamondP2PService] Checking quote token allowance...', {
      signerAddress,
      diamondAddress: NEXT_PUBLIC_DIAMOND_ADDRESS,
      quoteTokenAddress,
      requiredAmount: amount.toString(),
    });

    const currentAllowance = await quoteToken.allowance(
      signerAddress,
      NEXT_PUBLIC_DIAMOND_ADDRESS,
    );

    if (BigInt(currentAllowance.toString()) < amount) {
      console.log(
        '[DiamondP2PService] Insufficient allowance, approving unlimited amount...',
      );
      const tx = await quoteToken.approve(
        NEXT_PUBLIC_DIAMOND_ADDRESS,
        ethers.MaxUint256,
      );
      await tx.wait();
      console.log('[DiamondP2PService] Quote token approved.');
    } else {
      console.log(
        '[DiamondP2PService] Sufficient allowance, no approval needed.',
      );
    }
  }

  /**
   * Resolve the currently configured AuSys payment token from the Diamond.
   * Throws a clear user-facing error if it has not been configured.
   */
  private async getConfiguredPayTokenAddress(): Promise<string> {
    const diamond = this.context.getDiamond();
    const payToken = await diamond.getPayToken();

    if (!payToken || payToken === ethers.ZeroAddress) {
      throw new Error(
        'P2P payment token is not configured on this deployment. Please ask the contract owner to call setPayToken(...) on the Diamond before creating or accepting offers.',
      );
    }

    if (
      payToken.toLowerCase() !== NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS.toLowerCase()
    ) {
      console.warn(
        '[DiamondP2PService] Contract pay token differs from NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS. Using on-chain pay token.',
        {
          configuredInContract: payToken,
          configuredInFrontend: NEXT_PUBLIC_QUOTE_TOKEN_ADDRESS,
        },
      );
    }

    return payToken;
  }

  /**
   * Ensure the ERC1155 token contract has granted approval to the Diamond.
   * Needed for sell offers where the contract escrows the seller's tokens.
   * When the token IS the Diamond (AssetsFacet ERC1155), use the Diamond contract
   * from context so approval and readback use the same facet/ABI.
   */
  private async ensureERC1155Approval(tokenAddress: string): Promise<void> {
    const signer = this.context.getSigner();
    const signerAddress = await this.context.getSignerAddress();
    const diamondAddress = NEXT_PUBLIC_DIAMOND_ADDRESS;

    // When the token is the Diamond (P2P offers use Diamond as the ERC1155), use
    // the Diamond contract from context so setApprovalForAll/isApprovedForAll
    // hit AssetsFacet via the same proxy/ABI and storage is consistent.
    const isDiamondToken =
      tokenAddress.toLowerCase() === diamondAddress.toLowerCase();
    const erc1155 = isDiamondToken
      ? this.context.getDiamond()
      : 'getERC1155Contract' in this.context
        ? (this.context as any).getERC1155Contract(tokenAddress)
        : new ethers.Contract(tokenAddress, ERC1155_ABI, signer);

    console.log('[DiamondP2PService] Checking ERC1155 approval...', {
      tokenAddress,
      signerAddress,
      diamondAddress,
      isDiamondToken,
      erc1155Address: erc1155.target,
    });

    try {
      const isApproved = await erc1155.isApprovedForAll(
        signerAddress,
        diamondAddress,
      );

      console.log(
        '[DiamondP2PService] ERC1155 isApprovedForAll result:',
        isApproved,
      );

      if (!isApproved) {
        console.log(
          '[DiamondP2PService] ERC1155 not approved, requesting setApprovalForAll...',
        );
        const tx = await erc1155.setApprovalForAll(diamondAddress, true);
        const receipt = await tx.wait();
        console.log(
          '[DiamondP2PService] ERC1155 approval granted, tx:',
          receipt?.hash,
        );

        // Verify the approval took effect; retry with short delay to handle RPC propagation
        let verified = false;
        for (let attempt = 0; attempt < 3; attempt++) {
          if (attempt > 0) {
            await new Promise((r) => setTimeout(r, 500 * attempt));
          }
          verified = await erc1155.isApprovedForAll(
            signerAddress,
            diamondAddress,
          );
          if (verified) break;
        }
        console.log('[DiamondP2PService] ERC1155 approval verified:', verified);
        if (!verified) {
          console.error(
            '[DiamondP2PService] Approval failed - token:',
            tokenAddress,
            'signer:',
            signerAddress,
            'diamond:',
            diamondAddress,
          );
          throw new Error(
            `ERC1155 approval failed — setApprovalForAll did not take effect for token ${tokenAddress}`,
          );
        }
      } else {
        console.log(
          '[DiamondP2PService] ERC1155 already approved, no action needed.',
        );
      }
    } catch (error) {
      console.error('[DiamondP2PService] ERC1155 approval error:', error);
      throw new Error(
        `Failed to approve ERC1155 token for Diamond: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  /**
   * Cancel a P2P offer (only creator can cancel)
   * @param offerId The offer to cancel
   */
  async cancelOffer(offerId: string): Promise<void> {
    const diamond = this.context.getDiamond();

    console.log('[DiamondP2PService] Canceling P2P offer:', offerId);

    try {
      const tx = await diamond.cancelP2POffer(offerId);
      console.log('[DiamondP2PService] Transaction sent:', tx.hash);

      const receipt = await tx.wait();
      console.log('[DiamondP2PService] Offer canceled:', receipt.hash);
    } catch (error) {
      console.error('[DiamondP2PService] Error canceling offer:', error);
      const decoded = decodeP2PError(error);
      const wrapped = new Error(decoded);
      (wrapped as any).originalError = error;
      throw wrapped;
    }
  }
}

/**
 * Diamond-based implementation of P2P Repository (read operations)
 */
export class DiamondP2PRepository implements IP2PRepository {
  private context: DiamondContext;

  constructor(context: DiamondContext) {
    this.context = context;
  }

  /**
   * Get all open P2P offers
   */
  async getOpenOffers(): Promise<P2POffer[]> {
    const diamond = this.context.getDiamond();

    try {
      const offerIds: string[] = await diamond.getOpenP2POffers();
      console.log(
        '[DiamondP2PRepository] Found',
        offerIds.length,
        'open offers',
      );

      const offers = await Promise.all(offerIds.map((id) => this.getOffer(id)));

      return offers.filter((o): o is P2POffer => o !== null);
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting open offers:', error);
      return [];
    }
  }

  /**
   * Get P2P offers created by a specific user
   */
  async getUserOffers(userAddress: string): Promise<P2POffer[]> {
    const diamond = this.context.getDiamond();

    try {
      const offerIds: string[] = await diamond.getUserP2POffers(userAddress);
      console.log(
        '[DiamondP2PRepository] Found',
        offerIds.length,
        'offers for user',
        userAddress,
      );

      const offers = await Promise.all(offerIds.map((id) => this.getOffer(id)));

      return offers.filter((o): o is P2POffer => o !== null);
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting user offers:', error);
      return [];
    }
  }

  /**
   * Get a specific P2P offer by ID
   */
  async getOffer(offerId: string): Promise<P2POffer | null> {
    const diamond = this.context.getDiamond();

    try {
      const order = await diamond.getAuSysOrder(offerId);

      // Check if order exists (id will be zero hash if not found)
      if (order.id === ethers.ZeroHash) {
        return null;
      }

      const offer: P2POffer = {
        id: order.id,
        creator: order.isSellerInitiated ? order.seller : order.buyer,
        targetCounterparty:
          order.targetCounterparty === ethers.ZeroAddress
            ? null
            : order.targetCounterparty,
        token: order.token,
        tokenId: order.tokenId.toString(),
        quantity: BigInt(order.tokenQuantity.toString()),
        price: BigInt(order.price.toString()),
        txFee: BigInt(order.txFee.toString()),
        isSellerInitiated: order.isSellerInitiated,
        status: mapContractStatusToP2PStatus(Number(order.currentStatus)),
        buyer: order.buyer,
        seller: order.seller,
        createdAt: 0, // Not stored in contract, would need indexer
        expiresAt: Number(order.expiresAt),
        // Deep-copy locationData and nodes — ethers.js freezes contract return values
        locationData: order.locationData
          ? {
              startLocation: {
                lat: order.locationData.startLocation?.lat || '',
                lng: order.locationData.startLocation?.lng || '',
              },
              endLocation: {
                lat: order.locationData.endLocation?.lat || '',
                lng: order.locationData.endLocation?.lng || '',
              },
              startName: order.locationData.startName || '',
              endName: order.locationData.endName || '',
            }
          : undefined,
        nodes: [...(order.nodes || [])],
      };

      return offer;
    } catch (error) {
      console.error('[DiamondP2PRepository] Error getting offer:', error);
      return null;
    }
  }

  /**
   * Get offers filtered by asset
   */
  async getOffersByAsset(token: string, tokenId: string): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter(
      (o) =>
        o.token.toLowerCase() === token.toLowerCase() && o.tokenId === tokenId,
    );
  }

  /**
   * Get buy offers (offers from buyers looking to purchase)
   */
  async getBuyOffers(): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter((o) => !o.isSellerInitiated);
  }

  /**
   * Get sell offers (offers from sellers looking to sell)
   */
  async getSellOffers(): Promise<P2POffer[]> {
    const openOffers = await this.getOpenOffers();
    return openOffers.filter((o) => o.isSellerInitiated);
  }
}
