#!/usr/bin/env bun
/**
 * Generate Diamond ABI for Frontend
 *
 * This script generates a TypeScript file containing the Diamond ABI
 * by reading from extracted facet ABIs (from Hardhat artifacts).
 *
 * Flow:
 *   1. npx hardhat compile          → generates artifacts/
 *   2. bun extract-facet-abis.ts    → extracts to lib/contracts/facet-abis.json
 *   3. bun generate-diamond-abi.ts  → generates infrastructure/contracts/diamond-abi.generated.ts
 *
 * Or run all at once:
 *   npm run build:abis
 *
 * Usage:
 *   bun scripts/generate-diamond-abi.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FACET_ABIS_PATH = path.resolve(
  __dirname,
  '../lib/contracts/facet-abis.json',
);
const OUTPUT_PATH = path.resolve(
  __dirname,
  '../infrastructure/contracts/diamond-abi.generated.ts',
);

// Facets to include in the frontend Diamond ABI
const FRONTEND_FACETS = [
  'OrderRouterFacet', // Primary - use this for all order operations
  'CLOBFacet', // CLOB operations
  'NodesFacet', // Node management including supporting documents
  'DiamondLoupeFacet', // Diamond introspection
  'OwnershipFacet', // Ownership management
  'ERC1155ReceiverFacet', // ERC1155 token receiving
];

interface ABIItem {
  type: string;
  name?: string;
  inputs?: any[];
  outputs?: any[];
  stateMutability?: string;
  anonymous?: boolean;
}

function loadFacetABIs(): Record<string, ABIItem[]> {
  if (!fs.existsSync(FACET_ABIS_PATH)) {
    console.error(`❌ Facet ABIs not found at: ${FACET_ABIS_PATH}`);
    console.error('   Run "bun scripts/extract-facet-abis.ts" first.');
    process.exit(1);
  }

  const data = JSON.parse(fs.readFileSync(FACET_ABIS_PATH, 'utf8'));

  // Remove metadata key
  const { _metadata, ...facets } = data;

  if (_metadata) {
    console.log(`📁 Using facet ABIs extracted at: ${_metadata.extractedAt}`);
  }

  return facets;
}

function generateABIFile() {
  console.log('🔧 Generating Diamond ABI from extracted facet ABIs...\n');

  const facetABIs = loadFacetABIs();

  // Collect all ABI fragments from specified facets
  const combinedABI: ABIItem[] = [];
  const includedItems: Set<string> = new Set();

  for (const facetName of FRONTEND_FACETS) {
    const facetABI = facetABIs[facetName];
    if (!facetABI || facetABI.length === 0) {
      console.warn(
        `  ⚠ Facet ${facetName} not found or empty in facet-abis.json`,
      );
      continue;
    }

    let added = 0;
    for (const fragment of facetABI) {
      // Skip non-function/event items (like errors, constructors)
      if (fragment.type !== 'function' && fragment.type !== 'event') {
        continue;
      }

      // Deduplicate by type + name (some facets may have overlapping interfaces)
      const key = `${fragment.type}:${fragment.name}`;
      if (!includedItems.has(key)) {
        includedItems.add(key);
        combinedABI.push(fragment);
        added++;
      }
    }

    console.log(`  ✓ ${facetName}: ${added} items added`);
  }

  console.log(`\n📊 Total: ${combinedABI.length} ABI fragments`);

  // Generate TypeScript file
  const output = `/**
 * Diamond Contract ABI - Auto-generated
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * This file is generated from Hardhat artifacts via:
 *   1. npx hardhat compile
 *   2. bun scripts/extract-facet-abis.ts
 *   3. bun scripts/generate-diamond-abi.ts
 *
 * Or: npm run build:abis
 *
 * Generated: ${new Date().toISOString()}
 * Facets: ${FRONTEND_FACETS.join(', ')}
 */

import { ABIFragment } from '@/types/abi';

export const DIAMOND_ABI: ABIFragment[] = ${JSON.stringify(combinedABI, null, 2)} as const;

// Export individual facet ABIs for selective imports
${FRONTEND_FACETS.map(
  (facet) =>
    `export const ${facet.toUpperCase()}_ABI = ${JSON.stringify(facetABIs[facet] || [], null, 2)} as const;`,
).join('\n\n')}

// Helper to get ABI as ethers-compatible format
export function getEthersABI(): any[] {
  return DIAMOND_ABI as any[];
}
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`\n✅ Generated: ${OUTPUT_PATH}`);
}

generateABIFile();
