#!/usr/bin/env npx ts-node
/**
 * Generate Diamond ABI for Frontend
 *
 * This script generates a TypeScript file containing the Diamond ABI
 * from the single source of truth in deploy.config.ts
 *
 * Usage:
 *   npx ts-node scripts/generate-diamond-abi.ts
 *   # or
 *   npm run generate:abi
 */

import * as fs from 'fs';
import * as path from 'path';
import { FACET_ABI, ABIFragment } from './deploy.config';

const OUTPUT_PATH = path.resolve(
  __dirname,
  '../infrastructure/contracts/diamond-abi.generated.ts',
);

// Facets to include in the frontend Diamond ABI
const FRONTEND_FACETS = [
  'CLOBFacet',
  'NodesFacet',
  'DiamondLoupeFacet',
  'OwnershipFacet',
  'ERC1155ReceiverFacet',
];

function generateABIFile() {
  console.log('🔧 Generating Diamond ABI from deploy.config.ts...\n');

  // Collect all ABI fragments from specified facets
  const combinedABI: ABIFragment[] = [];
  const includedFunctions: Set<string> = new Set();

  for (const facetName of FRONTEND_FACETS) {
    const facetABI = FACET_ABI[facetName];
    if (!facetABI) {
      console.warn(`⚠️  Facet ${facetName} not found in FACET_ABI`);
      continue;
    }

    console.log(`  ✓ Including ${facetName} (${facetABI.length} fragments)`);

    for (const fragment of facetABI) {
      // Deduplicate by function name (some facets may have overlapping interfaces)
      const key =
        fragment.type === 'function'
          ? `fn:${fragment.name}`
          : `ev:${fragment.name}`;
      if (!includedFunctions.has(key)) {
        includedFunctions.add(key);
        combinedABI.push(fragment);
      }
    }
  }

  console.log(`\n📊 Total: ${combinedABI.length} ABI fragments`);

  // Generate TypeScript file
  const output = `/**
 * Diamond Contract ABI - Auto-generated
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * This file is generated from scripts/deploy.config.ts
 *
 * To regenerate:
 *   npx ts-node scripts/generate-diamond-abi.ts
 *
 * Generated: ${new Date().toISOString()}
 * Facets: ${FRONTEND_FACETS.join(', ')}
 */

import { ABIFragment } from '@/scripts/deploy.config';

export const DIAMOND_ABI: ABIFragment[] = ${JSON.stringify(combinedABI, null, 2)} as const;

// Export individual facet ABIs for selective imports
${FRONTEND_FACETS.map(
  (facet) =>
    `export const ${facet.toUpperCase()}_ABI = ${JSON.stringify(FACET_ABI[facet] || [], null, 2)} as const;`,
).join('\n\n')}

// Helper to get ABI as ethers-compatible format
export function getEthersABI(): any[] {
  return DIAMOND_ABI as any[];
}
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(OUTPUT_PATH, output);
  console.log(`\n✅ Generated: ${OUTPUT_PATH}`);
}

generateABIFile();
