#!/usr/bin/env npx ts-node
/**
 * Unified Deployment Script
 *
 * Features:
 *   - Deploy contracts using predefined modes (full, diamond, rwy, etc.)
 *   - Deploy individual contracts
 *   - Smart facet upgrades with automatic selector detection
 *   - Dry run mode to preview changes
 *
 * Usage (set environment variables for options):
 *   DEPLOY_MODE=full npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_MODE=diamond npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_MODE=rwy npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_CONTRACT=RWYStakingFacet npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_FACET=NodesFacet npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_FACET=CLOBFacet DEPLOY_ACTION=replace npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *   DEPLOY_LIST_MODES=true npx hardhat run scripts/unified-deploy.ts --network baseSepolia
 *
 * Environment Variables:
 *   DEPLOY_MODE         Deploy using a predefined mode (full, diamond, rwy, bridge, standalone, all)
 *   DEPLOY_CONTRACT     Deploy a single contract by name
 *   DEPLOY_FACET        Deploy/update a single facet (auto-detects selector changes by default)
 *   DEPLOY_ACTION       For facets: auto (default - smart detection), add, replace, or remove
 *   DEPLOY_LIST_MODES   Set to 'true' to list all available deployment modes
 *   DEPLOY_LIST_CONTRACTS Set to 'true' to list all available contracts
 *   DEPLOY_DRY_RUN      Set to 'true' for dry run without deploying
 *   DEPLOY_SKIP_CONFIG  Set to 'true' to skip updating config files
 *   DEPLOY_AUTO_WAIT_FOR_DIAMOND_CUT Set to 'true' to wait out diamond-cut timelocks in CI
 *
 * Smart Facet Upgrade (DEPLOY_ACTION=auto or omitted):
 *   When upgrading a facet, the script automatically:
 *   1. Queries the Diamond's on-chain state via DiamondLoupe
 *   2. Compares on-chain selectors with generated facet-selectors.json
 *   3. Determines which selectors need to be added, replaced, or removed
 *   4. Executes a single diamondCut with all necessary changes
 *
 * IMPORTANT: Before deploying, always run:
 *   npm run contract:gen
 * This regenerates selectors from Hardhat artifacts (the single source of truth)
 *
 *   This prevents issues where:
 *   - New functions are added to a facet but not registered in Diamond
 *   - Selectors still point to old facet addresses after deployment
 *   - Removed functions leave orphaned selectors
 */

import { artifacts, ethers, network } from 'hardhat';
import * as fs from 'fs';
import * as path from 'path';
import {
  CONTRACTS,
  DEPLOYMENT_MODES,
  DEPRECATED_SELECTORS,
  ContractConfig,
} from './deploy.config';
import {
  renderIndexerDiamondConstants,
  replaceChainConstant,
  ensureQuoteTokenRuntimeConfig,
} from './lib/deploy-config';
import { loadDeploymentManifest } from './lib/deployment-manifest';
import { planFacetSelectorAdditions } from './lib/facet-selector-install';
import { sendWithNonceRetry } from './lib/nonce-retry';
import {
  assertAddressHasContractCode,
  isProductionPayTokenChain,
  resolveExpectedPayToken,
} from './lib/pay-token';
import {
  readDiamondAddressFromChainConstants,
  resolveDiamondAddress as resolveRuntimeDiamondAddress,
} from './lib/runtime-contracts';
import {
  getSupportedAssetClasses,
  loadSupportedAssetCatalog,
} from './lib/supported-assets';

// =============================================================================
// FACET SELECTORS - Loaded from generated JSON (single source of truth)
// =============================================================================
// Generated by: npm run contract:gen (scripts/gen-all.ts)
// Source: Hardhat artifacts (artifacts/contracts/)

interface FacetSelectorsData {
  [facetName: string]: {
    selectors: { [functionName: string]: string };
    allSelectors: string[];
  };
}

const FACET_SELECTORS_PATH = path.join(
  __dirname,
  '../infrastructure/contracts/facet-selectors.generated.json',
);
const DEFAULT_SUPPORTED_ASSET_CLASSES = getSupportedAssetClasses(
  loadSupportedAssetCatalog(),
);

function loadFacetSelectors(): Record<string, string[]> {
  if (!fs.existsSync(FACET_SELECTORS_PATH)) {
    console.warn(
      '⚠️  facet-selectors.json not found. Run: npm run contract:gen',
    );
    return {};
  }

  const data: FacetSelectorsData = JSON.parse(
    fs.readFileSync(FACET_SELECTORS_PATH, 'utf8'),
  );

  // Convert to the legacy format (facetName -> array of selectors)
  const selectors: Record<string, string[]> = {};
  for (const [facetName, facetData] of Object.entries(data)) {
    selectors[facetName] = facetData.allSelectors;
  }

  return selectors;
}

// Load selectors at module initialization
const FACET_SELECTORS = loadFacetSelectors();

// =============================================================================
// TYPES
// =============================================================================

interface DeploymentResult {
  network: string;
  chainId: number;
  deployer: string;
  contracts: Record<string, { address: string; blockNumber: number }>;
  timestamp: string;
}

interface CLIArgs {
  mode?: string;
  contract?: string;
  facet?: string;
  action?: 'add' | 'replace' | 'remove' | 'auto';
  listModes?: boolean;
  listContracts?: boolean;
  dryRun?: boolean;
  skipConfig?: boolean;
}

type FacetCutInput = {
  facetAddress: string;
  action: number;
  functionSelectors: string[];
};

const DIAMOND_CUT_EXTENDED_ABI = [
  'function diamondCut((address facetAddress, uint8 action, bytes4[] functionSelectors)[] _diamondCut, address _init, bytes _calldata) external',
  'function scheduleDiamondCut((address facetAddress, uint8 action, bytes4[] functionSelectors)[] _diamondCut, address _init, bytes _calldata) external returns (bytes32 cutHash, uint256 executeAfter)',
  'function getDiamondCutTimelock() external view returns (uint256)',
  'function getPendingDiamondCut() external view returns (bytes32 cutHash, uint256 executeAfter)',
] as const;

// =============================================================================
// CLI ARGUMENT PARSING
// =============================================================================

function parseArgs(): CLIArgs {
  const args: CLIArgs = {};

  // Parse from environment variables (Hardhat doesn't pass CLI args well)
  if (process.env.DEPLOY_MODE) {
    args.mode = process.env.DEPLOY_MODE;
  }
  if (process.env.DEPLOY_CONTRACT) {
    args.contract = process.env.DEPLOY_CONTRACT;
  }
  if (process.env.DEPLOY_FACET) {
    args.facet = process.env.DEPLOY_FACET;
  }
  if (process.env.DEPLOY_ACTION) {
    args.action = process.env.DEPLOY_ACTION as
      | 'add'
      | 'replace'
      | 'remove'
      | 'auto';
  }
  if (process.env.DEPLOY_LIST_MODES === 'true') {
    args.listModes = true;
  }
  if (process.env.DEPLOY_LIST_CONTRACTS === 'true') {
    args.listContracts = true;
  }
  if (process.env.DEPLOY_DRY_RUN === 'true') {
    args.dryRun = true;
  }
  if (process.env.DEPLOY_SKIP_CONFIG === 'true') {
    args.skipConfig = true;
  }

  return args;
}

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

function printModes() {
  console.log('\n📋 Available Deployment Modes:\n');
  for (const [key, mode] of Object.entries(DEPLOYMENT_MODES)) {
    console.log(`  --mode ${key}`);
    console.log(`    ${mode.description}`);
    console.log(`    Contracts: ${mode.contracts.join(', ')}\n`);
  }
}

function printContracts() {
  console.log('\n📋 Available Contracts:\n');

  const categories = ['core', 'diamond', 'facet', 'standalone'] as const;

  for (const category of categories) {
    const contracts = Object.entries(CONTRACTS)
      .filter(([_, config]) => config.category === category)
      .map(([name]) => name);

    if (contracts.length > 0) {
      console.log(`  ${category.toUpperCase()}:`);
      contracts.forEach((name) => console.log(`    - ${name}`));
      console.log('');
    }
  }
}

async function getDeploymentBlock(
  tx: {
    wait: (confirmations?: number) => Promise<{ blockNumber: number }>;
  } | null,
): Promise<number> {
  try {
    if (!tx) return await ethers.provider.getBlockNumber();
    const receipt = await tx.wait(1);
    return receipt.blockNumber;
  } catch {
    return await ethers.provider.getBlockNumber();
  }
}

async function waitForConfirmations(
  tx: { wait: (confirmations?: number) => Promise<unknown> } | null,
  confirmations: number = 2,
): Promise<void> {
  try {
    if (!tx) return;
    console.log(`  Waiting for ${confirmations} confirmations...`);
    await tx.wait(confirmations);
    console.log('  ✓ Confirmed');
  } catch {
    console.warn('  Warning: Could not wait for all confirmations');
  }
}

async function resolveActiveDiamondAddress(): Promise<string> {
  const chainId = Number((await ethers.provider.getNetwork()).chainId);
  const manifest = loadDeploymentManifest({
    deploymentsDir: path.resolve(process.cwd(), 'deployments'),
    networkName: network.name,
    chainId,
  });
  const chainConstantsDiamondAddress = readDiamondAddressFromChainConstants(
    path.resolve(process.cwd(), 'chain-constants.ts'),
  );
  const diamondAddress = resolveRuntimeDiamondAddress({
    manifestDiamondAddress: manifest?.diamond,
    chainConstantsDiamondAddress,
    preferManifestOverChainConstants: true,
    env: process.env,
  });
  const code = await ethers.provider.getCode(diamondAddress);

  if (!code || code === '0x') {
    throw new Error(
      `Resolved Diamond address ${diamondAddress} has no code on ${network.name} (${chainId}). Provide DIAMOND_ADDRESS or ensure deployments/manifest.${network.name}.json is available.`,
    );
  }

  return diamondAddress;
}

/**
 * Extract function selectors directly from a compiled contract
 * This is used when FACET_ABI is not defined for a facet
 */
async function extractSelectorsFromContract(
  contractName: string,
): Promise<string[]> {
  try {
    const factory = await ethers.getContractFactory(contractName);
    const contractInterface = factory.interface;

    // Get all function fragments and extract their selectors
    const selectors: string[] = [];
    for (const fragment of contractInterface.fragments) {
      if (fragment.type === 'function') {
        const funcFragment = fragment as ethers.FunctionFragment;
        if (funcFragment.selector) {
          selectors.push(funcFragment.selector);
        }
      }
    }

    return selectors;
  } catch (error: any) {
    console.error(
      `   ⚠️  Could not extract selectors from ${contractName}: ${error.message}`,
    );
    return [];
  }
}

function shouldAutoWaitForDiamondCutTimelock(): boolean {
  return process.env.DEPLOY_AUTO_WAIT_FOR_DIAMOND_CUT === 'true';
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function computeDiamondCutHash(
  facetCuts: FacetCutInput[],
  init: string,
  calldata: string,
): string {
  const abiCoder = ethers.AbiCoder.defaultAbiCoder();
  return ethers.keccak256(
    abiCoder.encode(
      [
        'tuple(address facetAddress, uint8 action, bytes4[] functionSelectors)[]',
        'address',
        'bytes',
      ],
      [facetCuts, init, calldata],
    ),
  );
}

async function executeDiamondCutWithScheduling(
  diamondAddress: string,
  facetCuts: FacetCutInput[],
  init: string = ethers.ZeroAddress,
  calldata: string = '0x',
): Promise<void> {
  const [signer] = await ethers.getSigners();
  const diamondCut = new ethers.Contract(
    diamondAddress,
    DIAMOND_CUT_EXTENDED_ABI,
    signer,
  );
  const getPendingNonce = () => signer.getNonce('pending');

  const timelock = BigInt(await diamondCut.getDiamondCutTimelock());
  if (timelock === 0n) {
    const tx = await sendWithNonceRetry({
      label: 'diamondCut',
      getPendingNonce,
      logger: console,
      send: (overrides) =>
        diamondCut.diamondCut(facetCuts, init, calldata, overrides ?? {}),
    });
    await tx.wait();
    return;
  }

  const expectedCutHash = computeDiamondCutHash(facetCuts, init, calldata);
  let [pendingHash, pendingEta] = await diamondCut.getPendingDiamondCut();
  let pendingHashStr = String(pendingHash).toLowerCase();
  let pendingEtaBigInt = BigInt(pendingEta);

  if (pendingEtaBigInt === 0n) {
    console.log('   Scheduling diamond cut (timelock enabled)...');
    const scheduleTx = await sendWithNonceRetry({
      label: 'scheduleDiamondCut',
      getPendingNonce,
      logger: console,
      send: (overrides) =>
        diamondCut.scheduleDiamondCut(
          facetCuts,
          init,
          calldata,
          overrides ?? {},
        ),
    });
    await scheduleTx.wait();
    [pendingHash, pendingEta] = await diamondCut.getPendingDiamondCut();
    pendingHashStr = String(pendingHash).toLowerCase();
    pendingEtaBigInt = BigInt(pendingEta);
  }

  if (pendingHashStr !== expectedCutHash.toLowerCase()) {
    throw new Error(
      `Pending diamond cut does not match this deployment (pending=${pendingHashStr}, expected=${expectedCutHash}).`,
    );
  }

  const now = BigInt(Math.floor(Date.now() / 1000));
  if (pendingEtaBigInt > now) {
    const secondsRemaining = Number(pendingEtaBigInt - now);
    if (!shouldAutoWaitForDiamondCutTimelock()) {
      throw new Error(
        `Diamond cut scheduled but timelock is still active for ~${secondsRemaining}s. Set DEPLOY_AUTO_WAIT_FOR_DIAMOND_CUT=true to wait and execute automatically.`,
      );
    }

    console.log(
      `   Timelock active. Waiting ~${secondsRemaining}s before executing diamond cut...`,
    );
    while (true) {
      const current = Math.floor(Date.now() / 1000);
      const remaining = Number(pendingEtaBigInt) - current;
      if (remaining <= 0) break;
      await sleep(Math.min(remaining, 30) * 1000);
    }
  }

  console.log('   Executing scheduled diamond cut...');
  const executeTx = await sendWithNonceRetry({
    label: 'diamondCut',
    getPendingNonce,
    logger: console,
    send: (overrides) =>
      diamondCut.diamondCut(facetCuts, init, calldata, overrides ?? {}),
  });
  await executeTx.wait();
}

// =============================================================================
// CHAIN CONSTANTS UPDATE
// =============================================================================

function updateChainConstants(
  deployment: DeploymentResult,
  existingAddresses: Record<string, string>,
) {
  const constantsPath = path.resolve('./chain-constants.ts');

  if (!fs.existsSync(constantsPath)) {
    console.warn('⚠️  chain-constants.ts not found, creating new file');
  }

  // Read existing content or use template
  let content = fs.existsSync(constantsPath)
    ? fs.readFileSync(constantsPath, 'utf-8')
    : '';

  // Merge new addresses with existing
  const allAddresses = { ...existingAddresses };
  for (const [name, data] of Object.entries(deployment.contracts)) {
    const config = CONTRACTS[name];
    if (config?.chainConstantKey) {
      allAddresses[config.chainConstantKey] = data.address;
    }
  }

  // Build deployment blocks
  const deploymentBlocks: Record<string, number> = {};
  for (const [name, data] of Object.entries(deployment.contracts)) {
    const config = CONTRACTS[name];
    if (config?.indexerConfig?.startBlockKey) {
      deploymentBlocks[config.indexerConfig.startBlockKey] = data.blockNumber;
    }
  }

  // Update or create each constant
  for (const [key, value] of Object.entries(allAddresses)) {
    const updatedContent = replaceChainConstant(content, key, value);

    if (updatedContent !== content) {
      content = updatedContent;
    } else {
      // Guard: only insert if the key truly doesn't exist yet.
      // replaceChainConstant returns unchanged content when the regex didn't
      // match — but the constant may already be present in a different format.
      // Appending without this check causes duplicate export declarations.
      const existsCheck = new RegExp(`export const ${key}\\s*=`, 'm');
      if (!existsCheck.test(content)) {
        const sectionMarker = key.includes('DIAMOND')
          ? '// =============================================================================\n// EIP-2535 DIAMOND CONTRACTS'
          : key.includes('RWY')
            ? '// RWY Vault'
            : '// =============================================================================\n// CONTRACT ADDRESSES';
        const newLine = `export const ${key} =\n  '${value}';`;

        const insertIndex = content.indexOf(sectionMarker);
        if (insertIndex === -1) {
          content += `\n${newLine}\n`;
        }
      }
    }
  }

  // Update DEPLOYMENT_BLOCKS
  const existingBlocksMatch = content.match(
    /export const DEPLOYMENT_BLOCKS = \{([\s\S]*?)\};/,
  );
  let existingBlocks: Record<string, number> = {};

  if (existingBlocksMatch) {
    // Parse existing blocks
    const blocksContent = existingBlocksMatch[1];
    const blockLines = blocksContent.match(/(\w+):\s*(\d+)/g) || [];
    for (const line of blockLines) {
      const [key, value] = line.split(':').map((s) => s.trim());
      existingBlocks[key] = parseInt(value);
    }
  }

  // Merge with new blocks
  const mergedBlocks = { ...existingBlocks, ...deploymentBlocks };
  const blocksString = Object.entries(mergedBlocks)
    .map(([key, value]) => `  ${key}: ${value},`)
    .join('\n');

  const newBlocksSection = `export const DEPLOYMENT_BLOCKS = {\n${blocksString}\n};`;

  if (existingBlocksMatch) {
    content = content.replace(
      /export const DEPLOYMENT_BLOCKS = \{[\s\S]*?\};/,
      newBlocksSection,
    );
  } else {
    content += `\n\n${newBlocksSection}\n`;
  }

  // Update header timestamp
  const timestampRegex = /\/\/ Deployed: .*/;
  const newTimestamp = `// Deployed: ${deployment.timestamp}`;
  if (timestampRegex.test(content)) {
    content = content.replace(timestampRegex, newTimestamp);
  }

  // Keep quote token settings runtime-configurable across regenerations.
  content = ensureQuoteTokenRuntimeConfig(content);

  fs.writeFileSync(constantsPath, content);
  console.log('✅ Updated chain-constants.ts');
}

// =============================================================================
// INDEXER CONFIG UPDATE
// =============================================================================

function updateIndexerConfig(deployment: DeploymentResult) {
  // Update diamond-constants.ts
  const diamondConstantsPath = path.resolve('./indexer/diamond-constants.ts');

  if (deployment.contracts.Diamond) {
    const content = renderIndexerDiamondConstants({
      address: deployment.contracts.Diamond.address,
      blockNumber: deployment.contracts.Diamond.blockNumber,
      timestamp: deployment.timestamp,
    });
    fs.writeFileSync(diamondConstantsPath, content);
    console.log('✅ Updated indexer/diamond-constants.ts');
  }

  // Note: ponder.config.ts uses chain-constants.ts imports, so it auto-updates
  console.log('✅ Indexer will use updated chain-constants.ts');
}

// =============================================================================
// INDEXER GENERATION
// =============================================================================

function runIndexerGeneration(): void {
  console.log('\n🔧 Generating indexer from contract ABIs...\n');

  try {
    // Import and run the generator
    const { spawn } = require('child_process');

    const generateScript = path.resolve(__dirname, 'generate-indexer.ts');

    if (!fs.existsSync(generateScript)) {
      console.warn(
        '⚠️  generate-indexer.ts not found, skipping indexer generation',
      );
      return;
    }

    // Run the generator synchronously by requiring it
    // This ensures it completes before continuing
    console.log('   Running indexer generator...');

    // Clear require cache to get fresh generation
    delete require.cache[require.resolve('./generate-indexer')];

    // The generate-indexer script runs immediately when required
    // We just need to ensure it has access to the compiled artifacts
    require('./generate-indexer');

    console.log('   ✓ Indexer generated successfully');
  } catch (error: any) {
    // Generator might fail if artifacts aren't compiled yet
    // This is okay - user can run it manually after compiling
    console.warn(`⚠️  Could not generate indexer: ${error.message}`);
    console.log(
      '   Run manually after deployment: npx ts-node scripts/generate-indexer.ts',
    );
  }
}

// =============================================================================
// FRONTEND ABI GENERATION
// =============================================================================

function regenerateFrontendABI() {
  console.log('🔧 Regenerating frontend Diamond ABI...');

  try {
    // Import and run the generator
    const { FACET_ABI, ABIFragment } = require('./deploy.config');

    const FRONTEND_FACETS = [
      'CLOBFacet',
      'NodesFacet',
      'DiamondLoupeFacet',
      'OwnershipFacet',
      'ERC1155ReceiverFacet',
      'OrderRouterFacet',
      'AssetsFacet',
      'AuSysFacet',
      'AuSysAdminFacet',
      'AuSysViewFacet',
      'BridgeFacet',
      'RWYStakingFacet',
      'CLOBLogisticsFacet',
      'OperatorFacet',
    ];

    // Collect all ABI fragments
    const combinedABI: any[] = [];
    const includedFunctions = new Set<string>();

    for (const facetName of FRONTEND_FACETS) {
      let facetABI = FACET_ABI[facetName];
      if (!facetABI) {
        try {
          facetABI = artifacts.readArtifactSync(facetName).abi;
        } catch {
          continue;
        }
      }

      for (const fragment of facetABI) {
        const key =
          fragment.type === 'function'
            ? `fn:${fragment.name}`
            : `ev:${fragment.name}`;
        if (!includedFunctions.has(key)) {
          includedFunctions.add(key);
          combinedABI.push(fragment);
        }
      }
    }

    // Generate TypeScript file
    const outputPath = path.resolve(
      './infrastructure/contracts/diamond-abi.generated.ts',
    );
    const outputDir = path.dirname(outputPath);

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    const output = `/**
 * Diamond Contract ABI - Auto-generated
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 * This file is generated from scripts/deploy.config.ts
 *
 * To regenerate:
 *   npx ts-node scripts/generate-diamond-abi.ts
 *
 * Generated: ${new Date().toISOString()}
 * Facets: ${FRONTEND_FACETS.join(', ')}
 */

import { ABIFragment } from '@/scripts/deploy.config';

export const DIAMOND_ABI: ABIFragment[] = ${JSON.stringify(combinedABI, null, 2)} as const;

// Export individual facet ABIs for selective imports
${FRONTEND_FACETS.map((facet) => {
  let facetAbi = FACET_ABI[facet];
  if (!facetAbi) {
    try {
      facetAbi = artifacts.readArtifactSync(facet).abi;
    } catch {
      facetAbi = [];
    }
  }
  return `export const ${facet.toUpperCase()}_ABI = ${JSON.stringify(facetAbi || [], null, 2)} as const;`;
}).join('\n\n')}

// Helper to get ABI as ethers-compatible format
export function getEthersABI(): any[] {
  return DIAMOND_ABI as any[];
}
`;

    fs.writeFileSync(outputPath, output);
    console.log(
      '✅ Generated frontend ABI: infrastructure/contracts/diamond-abi.generated.ts',
    );
  } catch (error: any) {
    console.warn(`⚠️  Could not regenerate frontend ABI: ${error.message}`);
  }
}

// =============================================================================
// DEPLOYMENT FUNCTIONS
// =============================================================================

async function deployContract(
  config: ContractConfig,
  addresses: Record<string, string>,
  deployer: string,
): Promise<{ address: string; blockNumber: number }> {
  console.log(`\n📦 Deploying ${config.name}...`);

  const Factory = await ethers.getContractFactory(config.contractName);
  const [signer] = await ethers.getSigners();

  // Get constructor args
  const args = config.constructorArgs
    ? config.constructorArgs(addresses, deployer)
    : [];

  if (args.length > 0) {
    console.log(`   Constructor args: ${JSON.stringify(args)}`);
  }

  const contract = await sendWithNonceRetry({
    label: `deploy ${config.name}`,
    getPendingNonce: () => signer.getNonce('pending'),
    logger: console,
    send: (overrides) => Factory.deploy(...args, overrides ?? {}),
  });
  await waitForConfirmations(contract.deploymentTransaction());

  const address = await contract.getAddress();
  const blockNumber = await getDeploymentBlock(
    contract.deploymentTransaction(),
  );

  console.log(`   ✓ ${config.name}: ${address} (block ${blockNumber})`);

  // Run post-deploy hook if exists
  if (config.postDeploy) {
    await config.postDeploy(contract, addresses);
  }

  return { address, blockNumber };
}

async function deployMode(
  modeName: string,
  dryRun: boolean = false,
): Promise<DeploymentResult> {
  const mode = DEPLOYMENT_MODES[modeName];
  if (!mode) {
    throw new Error(
      `Unknown deployment mode: ${modeName}. Use --list-modes to see available modes.`,
    );
  }

  console.log(`\n🚀 ${mode.name}`);
  console.log(`   ${mode.description}`);
  console.log(`   Contracts: ${mode.contracts.join(', ')}\n`);

  if (dryRun) {
    console.log('🔍 DRY RUN - No contracts will be deployed\n');
    return {
      network: network.name,
      chainId: 0,
      deployer: '',
      contracts: {},
      timestamp: new Date().toISOString(),
    };
  }

  const [deployer] = await ethers.getSigners();
  const chainId = Number((await ethers.provider.getNetwork()).chainId);

  console.log(`Network: ${network.name} (Chain ID: ${chainId})`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(
    `Balance: ${ethers.formatEther(await deployer.provider.getBalance(deployer.address))} ETH\n`,
  );

  const addresses: Record<string, string> = {};
  const deployedContracts: Record<
    string,
    { address: string; blockNumber: number }
  > = {};

  // Deploy contracts in order (respecting dependencies)
  for (const contractName of mode.contracts) {
    const config = CONTRACTS[contractName];
    if (!config) {
      console.warn(`⚠️  Unknown contract: ${contractName}, skipping`);
      continue;
    }

    // Check dependencies
    if (config.dependencies) {
      for (const dep of config.dependencies) {
        if (!addresses[dep]) {
          throw new Error(
            `Dependency ${dep} not deployed yet for ${contractName}`,
          );
        }
      }
    }

    const result = await deployContract(config, addresses, deployer.address);
    addresses[contractName] = result.address;
    deployedContracts[contractName] = result;

    // Small delay between deployments to prevent nonce race conditions on fast networks (Arbitrum, etc.)
    await new Promise((resolve) => setTimeout(resolve, 2000));
  }

  // Handle Diamond facet installation if Diamond was deployed
  if (deployedContracts.Diamond && modeName.includes('diamond')) {
    await installFacetsToDiamond(addresses, deployedContracts, mode.contracts);
  }

  // Post-deployment configuration
  await postDeploymentConfig(addresses, deployer.address);

  // Generate indexer from new contract ABIs (if deploying facets)
  const deployedFacets = mode.contracts.filter((name) =>
    name.endsWith('Facet'),
  );
  if (deployedFacets.length > 0 && !dryRun) {
    runIndexerGeneration();
  }

  return {
    network: network.name,
    chainId,
    deployer: deployer.address,
    contracts: deployedContracts,
    timestamp: new Date().toISOString(),
  };
}

async function installFacetsToDiamond(
  addresses: Record<string, string>,
  deployedContracts: Record<string, { address: string; blockNumber: number }>,
  modeContracts: string[],
) {
  console.log('\n⚙️  Installing facets to Diamond...\n');
  void deployedContracts;

  // Derive facets to install from the deployment mode's contract list.
  // This is the single source of truth - adding a facet to a deployment mode
  // automatically includes it in the Diamond cut. No hardcoded lists to maintain.
  // DiamondCutFacet is excluded because it's already added in the Diamond constructor.
  const CONSTRUCTOR_FACETS = ['DiamondCutFacet'];
  const facetsToInstall = modeContracts.filter(
    (name) =>
      CONTRACTS[name]?.category === 'facet' &&
      !CONSTRUCTOR_FACETS.includes(name),
  );

  console.log(`   Facets to install: ${facetsToInstall.join(', ')}\n`);

  const diamondLoupe = await ethers.getContractAt(
    'IDiamondLoupe',
    addresses.Diamond,
  );
  const activeSelectors = new Set<string>();
  const facets = await diamondLoupe.facets();

  for (const facet of facets) {
    for (const selector of facet.functionSelectors) {
      activeSelectors.add(selector.toLowerCase());
    }
  }

  for (const facetName of facetsToInstall) {
    if (!addresses[facetName] || !FACET_SELECTORS[facetName]) continue;

    console.log(`   Adding ${facetName}...`);
    const rawSelectors = FACET_SELECTORS[facetName];
    const { selectorsToAdd, duplicateCount, alreadyInstalledCount } =
      planFacetSelectorAdditions({
        selectors: rawSelectors,
        activeSelectors,
      });

    if (duplicateCount > 0) {
      console.log(
        `   ⚠️  Removed ${duplicateCount} duplicate selector(s) from ${facetName}`,
      );
    }

    if (alreadyInstalledCount > 0) {
      console.log(
        `   ⚠️  Skipping ${alreadyInstalledCount} selector(s) already installed on the Diamond`,
      );
    }

    if (selectorsToAdd.length === 0) {
      console.log(`   ✓ No new selectors to add for ${facetName}`);
      continue;
    }

    try {
      await executeDiamondCutWithScheduling(addresses.Diamond, [
        {
          facetAddress: addresses[facetName],
          action: 0, // Add
          functionSelectors: selectorsToAdd,
        },
      ]);
      selectorsToAdd.forEach((selector) =>
        activeSelectors.add(selector.toLowerCase()),
      );
      console.log(`   ✓ Added ${selectorsToAdd.length} selectors`);
    } catch (error: any) {
      throw new Error(`Failed to install ${facetName}: ${error.message}`);
    }
  }
}

async function postDeploymentConfig(
  addresses: Record<string, string>,
  deployer: string,
) {
  console.log('\n⚙️  Post-deployment configuration...\n');
  const activeChainId = Number((await ethers.provider.getNetwork()).chainId);

  // Merge addresses deployed in this run with already-known addresses from
  // chain-constants.ts so partial deploy modes can still run full configuration.
  const existingAddresses = loadExistingAddresses();
  const resolvedAddresses: Record<string, string> = { ...addresses };
  for (const [name, cfg] of Object.entries(CONTRACTS)) {
    if (
      !resolvedAddresses[name] &&
      cfg.chainConstantKey &&
      existingAddresses[cfg.chainConstantKey]
    ) {
      resolvedAddresses[name] = existingAddresses[cfg.chainConstantKey];
    }
  }
  const shouldForceProductionPayToken =
    isProductionPayTokenChain(activeChainId);
  const expectedPayToken = resolvedAddresses.Diamond
    ? resolveExpectedPayToken({
        chainId: activeChainId,
        fallbackTokenAddress: resolvedAddresses.Aura,
      })
    : null;

  if (expectedPayToken) {
    await assertAddressHasContractCode(
      ethers.provider,
      expectedPayToken,
      'Expected pay token',
    );
  }

  // Set AuraAsset address in Diamond's NodesFacet storage
  if (resolvedAddresses.Diamond && resolvedAddresses.AuraAsset) {
    console.log('   Setting AuraAsset address in Diamond...');
    const diamond = await ethers.getContractAt(
      'NodesFacet',
      resolvedAddresses.Diamond,
    );
    try {
      const [signer] = await ethers.getSigners();
      const tx = await sendWithNonceRetry({
        label: 'NodesFacet.setAuraAssetAddress',
        getPendingNonce: () => signer.getNonce('pending'),
        logger: console,
        send: (overrides) =>
          diamond.setAuraAssetAddress(
            resolvedAddresses.AuraAsset,
            overrides ?? {},
          ),
      });
      await tx.wait();
      console.log('   ✓ AuraAsset address set in Diamond');
    } catch (e: any) {
      // Might already be set or function might not exist
      if (!e.message.includes('already set')) {
        console.log(`   ⚠️  Could not set AuraAsset address: ${e.message}`);
      }
    }
  }

  // Add default asset classes to Diamond's AssetsFacet
  if (resolvedAddresses.Diamond) {
    console.log('   Adding default asset classes to Diamond...');
    const assetsFacet = await ethers.getContractAt(
      'AssetsFacet',
      resolvedAddresses.Diamond,
    );

    let addedCount = 0;

    for (const className of DEFAULT_SUPPORTED_ASSET_CLASSES) {
      try {
        const [signer] = await ethers.getSigners();
        const tx = await sendWithNonceRetry({
          label: `AssetsFacet.addSupportedClass(${className})`,
          getPendingNonce: () => signer.getNonce('pending'),
          logger: console,
          send: (overrides) =>
            assetsFacet.addSupportedClass(className, overrides ?? {}),
        });
        await tx.wait();
        console.log(`   ✓ Added class: ${className}`);
        addedCount++;
      } catch (e: any) {
        if (
          e.message.includes('ClassAlreadyExists') ||
          e.message.includes('already')
        ) {
          // Class already exists, skip silently
        } else {
          console.log(`   ⚠️  Could not add class ${className}: ${e.message}`);
        }
      }
    }

    if (addedCount > 0) {
      console.log(`   ✓ Added ${addedCount} asset classes`);
    } else {
      console.log('   ✓ All default asset classes already exist');
    }
  }

  // Configure AuSysFacet payment token for P2P escrows.
  // Required for buy-offer creation and sell-offer acceptance.
  if (resolvedAddresses.Diamond && expectedPayToken) {
    console.log('   Configuring AuSys pay token on Diamond...');
    try {
      const auSysAdminFacet = await ethers.getContractAt(
        'AuSysAdminFacet',
        resolvedAddresses.Diamond,
      );
      const auSysViewFacet = await ethers.getContractAt(
        'AuSysViewFacet',
        resolvedAddresses.Diamond,
      );
      const currentPayToken = await auSysViewFacet.getPayToken();
      const isUnset = currentPayToken === ethers.ZeroAddress;
      const isMismatch =
        currentPayToken.toLowerCase() !== expectedPayToken.toLowerCase();
      const shouldSetPayToken =
        isUnset || (shouldForceProductionPayToken && isMismatch);

      if (shouldSetPayToken) {
        if (isMismatch && shouldForceProductionPayToken) {
          console.log(
            `   ⚠️  AuSys pay token mismatch on chain ${activeChainId}. Correcting ${currentPayToken} -> ${expectedPayToken}`,
          );
        }
        const [signer] = await ethers.getSigners();
        const tx = await sendWithNonceRetry({
          label: 'AuSysAdminFacet.setPayToken',
          getPendingNonce: () => signer.getNonce('pending'),
          logger: console,
          send: (overrides) =>
            auSysAdminFacet.setPayToken(expectedPayToken, overrides ?? {}),
        });
        await tx.wait();
        console.log(`   ✓ AuSys pay token set to ${expectedPayToken}`);
      } else if (isMismatch) {
        console.log(
          `   ⚠️  AuSys pay token already set to ${currentPayToken} (not overwriting with ${expectedPayToken})`,
        );
      } else {
        console.log('   ✓ AuSys pay token already configured');
      }
    } catch (e: any) {
      console.log(`   ⚠️  Could not configure AuSys pay token: ${e.message}`);
    }
  }

  // Configure RWY staking defaults so feature works without separate scripts.
  if (resolvedAddresses.Diamond) {
    console.log('   Configuring RWY staking defaults on Diamond...');
    try {
      const rwyFacet = await ethers.getContractAt(
        'RWYStakingFacet',
        resolvedAddresses.Diamond,
      );

      // Initialize defaults only when unset.
      try {
        const cfg = await rwyFacet.getRWYConfig();
        if (cfg[0] === 0n || cfg[1] === 0n || cfg[2] === 0n || cfg[3] === 0n) {
          const [signer] = await ethers.getSigners();
          const tx = await sendWithNonceRetry({
            label: 'RWYStakingFacet.initializeRWYStaking',
            getPendingNonce: () => signer.getNonce('pending'),
            logger: console,
            send: (overrides) => rwyFacet.initializeRWYStaking(overrides ?? {}),
          });
          await tx.wait();
          console.log('   ✓ Initialized RWY staking defaults');
        } else {
          console.log('   ✓ RWY staking defaults already initialized');
        }
      } catch (initError: any) {
        console.log(
          `   ⚠️  Could not initialize RWY staking defaults: ${initError.message}`,
        );
      }

      // Set RWY quote token if unset.
      if (expectedPayToken) {
        try {
          const currentQuote = await rwyFacet.getRWYQuoteToken();
          const isUnset = currentQuote === ethers.ZeroAddress;
          const isMismatch =
            currentQuote.toLowerCase() !== expectedPayToken.toLowerCase();
          const shouldSetQuoteToken =
            isUnset || (shouldForceProductionPayToken && isMismatch);

          if (shouldSetQuoteToken) {
            if (isMismatch && shouldForceProductionPayToken) {
              console.log(
                `   ⚠️  RWY quote token mismatch on chain ${activeChainId}. Correcting ${currentQuote} -> ${expectedPayToken}`,
              );
            }
            const [signer] = await ethers.getSigners();
            const tx = await sendWithNonceRetry({
              label: 'RWYStakingFacet.setRWYQuoteToken',
              getPendingNonce: () => signer.getNonce('pending'),
              logger: console,
              send: (overrides) =>
                rwyFacet.setRWYQuoteToken(expectedPayToken, overrides ?? {}),
            });
            await tx.wait();
            console.log(`   ✓ RWY quote token set to ${expectedPayToken}`);
          } else if (isMismatch) {
            console.log(
              `   ⚠️  RWY quote token already set to ${currentQuote} (not overwriting with ${expectedPayToken})`,
            );
          } else {
            console.log('   ✓ RWY quote token already configured');
          }
        } catch (quoteErr: any) {
          console.log(
            `   ⚠️  Could not configure RWY quote token: ${quoteErr.message}`,
          );
        }
      }

      // Set RWY CLOB address if available and currently unset.
      if (resolvedAddresses.CLOB) {
        try {
          const currentClob = await rwyFacet.getRWYCLOBAddress();
          if (currentClob === ethers.ZeroAddress) {
            const [signer] = await ethers.getSigners();
            const tx = await sendWithNonceRetry({
              label: 'RWYStakingFacet.setRWYCLOBAddress',
              getPendingNonce: () => signer.getNonce('pending'),
              logger: console,
              send: (overrides) =>
                rwyFacet.setRWYCLOBAddress(
                  resolvedAddresses.CLOB,
                  overrides ?? {},
                ),
            });
            await tx.wait();
            console.log(
              `   ✓ RWY CLOB address set to ${resolvedAddresses.CLOB}`,
            );
          } else {
            console.log('   ✓ RWY CLOB address already configured');
          }
        } catch (clobErr: any) {
          console.log(
            `   ⚠️  Could not configure RWY CLOB address: ${clobErr.message}`,
          );
        }
      }

      // Set RWY fee recipient if unset.
      try {
        const currentRecipient = await rwyFacet.getRWYFeeRecipient();
        if (currentRecipient === ethers.ZeroAddress) {
          const [signer] = await ethers.getSigners();
          const tx = await sendWithNonceRetry({
            label: 'RWYStakingFacet.setRWYFeeRecipient',
            getPendingNonce: () => signer.getNonce('pending'),
            logger: console,
            send: (overrides) =>
              rwyFacet.setRWYFeeRecipient(deployer, overrides ?? {}),
          });
          await tx.wait();
          console.log(`   ✓ RWY fee recipient set to ${deployer}`);
        } else {
          console.log('   ✓ RWY fee recipient already configured');
        }
      } catch (feeErr: any) {
        console.log(
          `   ⚠️  Could not configure RWY fee recipient: ${feeErr.message}`,
        );
      }
    } catch (e: any) {
      console.log(
        `   ⚠️  RWYStakingFacet configuration skipped/unavailable: ${e.message}`,
      );
    }
  }
}

async function deploySingleContract(
  contractName: string,
  dryRun: boolean = false,
): Promise<DeploymentResult> {
  const config = CONTRACTS[contractName];
  if (!config) {
    throw new Error(
      `Unknown contract: ${contractName}. Use --list-contracts to see available contracts.`,
    );
  }

  console.log(`\n🚀 Deploying single contract: ${contractName}\n`);

  if (dryRun) {
    console.log('🔍 DRY RUN - Contract will not be deployed\n');
    return {
      network: network.name,
      chainId: 0,
      deployer: '',
      contracts: {},
      timestamp: new Date().toISOString(),
    };
  }

  const [deployer] = await ethers.getSigners();
  const chainId = Number((await ethers.provider.getNetwork()).chainId);

  console.log(`Network: ${network.name} (Chain ID: ${chainId})`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(
    `Balance: ${ethers.formatEther(await deployer.provider.getBalance(deployer.address))} ETH\n`,
  );

  // Load existing addresses from chain-constants.ts
  const existingAddresses = loadExistingAddresses();

  // Check dependencies
  if (config.dependencies) {
    for (const dep of config.dependencies) {
      const depConfig = CONTRACTS[dep];
      if (
        depConfig?.chainConstantKey &&
        !existingAddresses[depConfig.chainConstantKey]
      ) {
        console.warn(`⚠️  Dependency ${dep} not found in chain-constants.ts`);
        console.warn(
          `   You may need to deploy it first or the deployment may fail.`,
        );
      }
    }
  }

  // Map existing addresses to contract names
  const addresses: Record<string, string> = {};
  for (const [name, cfg] of Object.entries(CONTRACTS)) {
    if (cfg.chainConstantKey && existingAddresses[cfg.chainConstantKey]) {
      addresses[name] = existingAddresses[cfg.chainConstantKey];
    }
  }

  const result = await deployContract(config, addresses, deployer.address);

  // Add the new contract to addresses for post-deployment config
  addresses[contractName] = result.address;

  // Run post-deployment configuration (sets NodeManager, etc.)
  await postDeploymentConfig(addresses, deployer.address);

  // Generate indexer from new contract ABIs
  if (contractName.endsWith('Facet') && !dryRun) {
    runIndexerGeneration();
  }

  return {
    network: network.name,
    chainId,
    deployer: deployer.address,
    contracts: { [contractName]: result },
    timestamp: new Date().toISOString(),
  };
}

function loadExistingAddresses(): Record<string, string> {
  const constantsPath = path.resolve('./chain-constants.ts');
  const addresses: Record<string, string> = {};

  if (!fs.existsSync(constantsPath)) return addresses;

  const content = fs.readFileSync(constantsPath, 'utf-8');
  // Match both direct assignments: export const X = '0x...'
  // and env fallbacks: export const X = process.env.X || '0x...'
  const regex =
    /export const (NEXT_PUBLIC_\w+)\s*=\s*(?:['"]([^'"]+)['"]|[^;]*\|\|\s*['"]([^'"]+)['"])/g;

  let match;
  while ((match = regex.exec(content)) !== null) {
    addresses[match[1]] = match[2] || match[3]; // match[2] for direct, match[3] for env fallback
  }

  return addresses;
}

/**
 * Analyzes on-chain Diamond state to determine which selectors need to be added, replaced, or removed
 */
async function analyzeSelectorsForFacet(
  diamondAddress: string,
  facetName: string,
  newFacetAddress: string,
  providedSelectors?: string[],
): Promise<{
  toAdd: string[];
  toReplace: string[];
  toRemove: string[];
  unchanged: string[];
  existingFacetAddress: string | null;
}> {
  const diamondLoupe = await ethers.getContractAt(
    'IDiamondLoupe',
    diamondAddress,
  );
  // Use provided selectors if given, otherwise fall back to FACET_SELECTORS
  const configSelectors = providedSelectors || FACET_SELECTORS[facetName] || [];

  const toAdd: string[] = [];
  const toReplace: string[] = [];
  const toRemove: string[] = [];
  const unchanged: string[] = [];

  // Build a full selector map from facets() for stale-selector removal detection
  const facets = await diamondLoupe.facets();
  const existingSelectorsMap = new Map<string, string>(); // selector -> facetAddress

  for (const facet of facets) {
    for (const selector of facet.functionSelectors) {
      existingSelectorsMap.set(
        selector.toLowerCase(),
        facet.facetAddress.toLowerCase(),
      );
    }
  }

  // Get the existing facet address from chain-constants (if any)
  const existingAddresses = loadExistingAddresses();
  const existingFacetAddress =
    existingAddresses[CONTRACTS[facetName]?.chainConstantKey || ''] || null;

  // Analyze each selector using authoritative per-selector facetAddress() lookup.
  // This is more reliable than the bulk facets() map, which can miss selectors
  // that were "stolen" by a previous facet's REPLACE operation in the same session.
  for (const selector of configSelectors) {
    let currentFacetAddr: string;
    try {
      currentFacetAddr = (
        await diamondLoupe.facetAddress(selector)
      ).toLowerCase();
    } catch {
      currentFacetAddr = ethers.ZeroAddress.toLowerCase();
    }

    if (currentFacetAddr === ethers.ZeroAddress.toLowerCase()) {
      // Selector doesn't exist in Diamond at all — add it
      toAdd.push(selector);
    } else if (
      newFacetAddress !== ethers.ZeroAddress &&
      currentFacetAddr !== newFacetAddress.toLowerCase()
    ) {
      // Selector exists but under a different address — replace it
      toReplace.push(selector);
    } else if (currentFacetAddr === newFacetAddress.toLowerCase()) {
      // Already pointing at the new facet — nothing to do
      unchanged.push(selector);
    } else {
      // Dry-run (newFacetAddress is ZeroAddress) — treat as needing replacement
      toReplace.push(selector);
    }
  }

  // Detect stale selectors: selectors registered under the OLD facet address
  // that are no longer in our config (need to be removed)
  if (existingFacetAddress) {
    const configLower = new Set(configSelectors.map((s) => s.toLowerCase()));
    for (const [selector, facetAddr] of existingSelectorsMap) {
      if (
        facetAddr === existingFacetAddress.toLowerCase() &&
        !configLower.has(selector)
      ) {
        toRemove.push(selector);
      }
    }
  }

  return { toAdd, toReplace, toRemove, unchanged, existingFacetAddress };
}

/**
 * Find deprecated selectors that are currently active in the Diamond
 * These should be automatically removed during any facet upgrade
 */
async function findActiveDeprecatedSelectors(
  diamondAddress: string,
): Promise<{ selector: string; functionName: string; reason: string }[]> {
  const diamondLoupe = await ethers.getContractAt(
    'IDiamondLoupe',
    diamondAddress,
  );

  const activeDeprecated: {
    selector: string;
    functionName: string;
    reason: string;
  }[] = [];

  // Get all selectors from the Diamond
  const facets = await diamondLoupe.facets();
  const existingSelectors = new Set<string>();

  for (const facet of facets) {
    for (const selector of facet.functionSelectors) {
      existingSelectors.add(selector.toLowerCase());
    }
  }

  // Check each deprecated selector
  for (const deprecated of DEPRECATED_SELECTORS) {
    // Compute selector from function signature if not provided
    let selector = deprecated.selector;
    if (selector === '0x' || !selector.startsWith('0x')) {
      // We need to compute it - for now, we'll use the function name
      // In production, this should be computed from the full signature
      // For the known deprecated functions, we can hardcode them:
      const knownSelectors: Record<string, string> = {
        // placeNodeSellOrder(address,address,uint256,address,uint256,uint256)
        placeNodeSellOrder: '0x', // Will be computed
        // placeBuyOrder(address,uint256,address,uint256,uint256)
        placeBuyOrder: '0x',
        // placeOrder(bytes32,uint256,uint256,bool,uint8)
        placeOrder: '0x',
      };
      selector = knownSelectors[deprecated.functionName] || '0x';
    }

    if (selector !== '0x' && existingSelectors.has(selector.toLowerCase())) {
      activeDeprecated.push({
        selector,
        functionName: deprecated.functionName,
        reason: deprecated.reason,
      });
    }
  }

  return activeDeprecated;
}

/**
 * Remove deprecated selectors from the Diamond
 */
async function removeDeprecatedSelectors(
  diamondAddress: string,
  dryRun: boolean = false,
): Promise<string[]> {
  console.log('\n🔍 Checking for deprecated selectors...\n');

  const activeDeprecated = await findActiveDeprecatedSelectors(diamondAddress);

  if (activeDeprecated.length === 0) {
    console.log('   ✓ No deprecated selectors found in Diamond\n');
    return [];
  }

  console.log(
    `   ⚠️  Found ${activeDeprecated.length} deprecated selector(s):\n`,
  );
  for (const dep of activeDeprecated) {
    console.log(`      ${dep.functionName} (${dep.selector})`);
    console.log(`         Reason: ${dep.reason}\n`);
  }

  if (dryRun) {
    console.log('   [DRY RUN] Would remove these deprecated selectors\n');
    return activeDeprecated.map((d) => d.selector);
  }

  const facetCuts = [
    {
      facetAddress: ethers.ZeroAddress,
      action: 2, // Remove
      functionSelectors: activeDeprecated.map((d) => d.selector),
    },
  ];

  console.log('   Removing deprecated selectors...');
  await executeDiamondCutWithScheduling(
    diamondAddress,
    facetCuts as FacetCutInput[],
  );
  console.log('   ✓ Deprecated selectors removed\n');

  return activeDeprecated.map((d) => d.selector);
}

async function updateFacet(
  facetName: string,
  action: 'add' | 'replace' | 'remove' | 'auto',
  dryRun: boolean = false,
): Promise<DeploymentResult> {
  const config = CONTRACTS[facetName];
  if (!config || config.category !== 'facet') {
    throw new Error(
      `${facetName} is not a valid facet. Use --list-contracts to see available facets.`,
    );
  }

  console.log(`\n🚀 ${action.toUpperCase()} Facet: ${facetName}\n`);

  const [deployer] = await ethers.getSigners();
  const chainId = Number((await ethers.provider.getNetwork()).chainId);
  const existingAddresses = loadExistingAddresses();
  const diamondAddress = await resolveActiveDiamondAddress();

  console.log(`Network: ${network.name} (Chain ID: ${chainId})`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Diamond: ${diamondAddress}\n`);

  // Build contract-name keyed addresses from chain constants so facet upgrades
  // can reuse postDeploymentConfig() the same way deploy modes do.
  const configAddresses: Record<string, string> = {};
  for (const [name, cfg] of Object.entries(CONTRACTS)) {
    if (cfg.chainConstantKey && existingAddresses[cfg.chainConstantKey]) {
      configAddresses[name] = existingAddresses[cfg.chainConstantKey];
    }
  }

  // Always extract selectors from the compiled artifact for facet upgrades.
  // This avoids drift when functions are split across facets but deploy.config.ts
  // has not been manually reshaped yet.
  let selectors = await extractSelectorsFromContract(config.contractName);
  if (selectors.length === 0) {
    selectors = FACET_SELECTORS[facetName];
  }
  if (!selectors || selectors.length === 0) {
    throw new Error(`Could not extract selectors for ${facetName}`);
  }
  console.log(
    `   ✓ Using ${selectors.length} selectors from ${config.contractName}\n`,
  );

  let facetAddress = ethers.ZeroAddress;
  let blockNumber = 0;

  // Deploy new facet if not removing
  if (action !== 'remove') {
    console.log(`📦 Deploying new ${facetName}...`);

    if (dryRun) {
      console.log('   [DRY RUN] Would deploy facet contract\n');
      facetAddress = '0x' + '0'.repeat(40);
    } else {
      const Factory = await ethers.getContractFactory(config.contractName);
      const facet = await sendWithNonceRetry({
        label: `deploy ${facetName}`,
        getPendingNonce: () => deployer.getNonce('pending'),
        logger: console,
        send: (overrides) => Factory.deploy(overrides ?? {}),
      });
      await waitForConfirmations(facet.deploymentTransaction());
      facetAddress = await facet.getAddress();
      blockNumber = await getDeploymentBlock(facet.deploymentTransaction());
      console.log(
        `   ✓ ${facetName}: ${facetAddress} (block ${blockNumber})\n`,
      );
    }
  }

  // If action is 'auto', analyze and perform smart update
  if (action === 'auto') {
    // First, check for and remove any deprecated selectors
    await removeDeprecatedSelectors(diamondAddress, dryRun);

    console.log('🔍 Analyzing on-chain selector state...\n');

    const analysis = await analyzeSelectorsForFacet(
      diamondAddress,
      facetName,
      facetAddress,
      selectors, // Pass the selectors (either from FACET_ABI or auto-extracted)
    );

    if (analysis.existingFacetAddress) {
      console.log(`   Current facet address: ${analysis.existingFacetAddress}`);
    }
    console.log(`   New facet address:     ${facetAddress}`);
    console.log('');
    console.log(`   Selectors to ADD:     ${analysis.toAdd.length}`);
    console.log(`   Selectors to REPLACE: ${analysis.toReplace.length}`);
    console.log(`   Selectors to REMOVE:  ${analysis.toRemove.length}`);
    console.log(`   Selectors unchanged:  ${analysis.unchanged.length}\n`);

    if (
      analysis.toAdd.length === 0 &&
      analysis.toReplace.length === 0 &&
      analysis.toRemove.length === 0
    ) {
      console.log(
        '✅ All selectors already point to correct facet. No changes needed.\n',
      );
      // Still run post-deploy config for facet upgrades so any required
      // idempotent setup is applied even when selector state is unchanged.
      if (!dryRun) {
        await postDeploymentConfig(configAddresses, deployer.address);
      }
      return {
        network: network.name,
        chainId,
        deployer: deployer.address,
        contracts: {},
        timestamp: new Date().toISOString(),
      };
    }

    if (dryRun) {
      console.log('🔍 DRY RUN - Would perform the following diamond cuts:\n');
      if (analysis.toAdd.length > 0) {
        console.log(`   ADD ${analysis.toAdd.length} selectors:`);
        analysis.toAdd.forEach((s) => console.log(`      ${s}`));
      }
      if (analysis.toReplace.length > 0) {
        console.log(`   REPLACE ${analysis.toReplace.length} selectors:`);
        analysis.toReplace.forEach((s) => console.log(`      ${s}`));
      }
      if (analysis.toRemove.length > 0) {
        console.log(`   REMOVE ${analysis.toRemove.length} selectors:`);
        analysis.toRemove.forEach((s) => console.log(`      ${s}`));
      }
      console.log('');
      return {
        network: network.name,
        chainId: 0,
        deployer: '',
        contracts: {},
        timestamp: new Date().toISOString(),
      };
    }

    const facetCuts: Array<{
      facetAddress: string;
      action: number;
      functionSelectors: string[];
    }> = [];

    // Build facet cuts array
    // Order matters: Remove first, then Replace, then Add
    // This prevents "selector already exists" errors

    if (analysis.toRemove.length > 0) {
      facetCuts.push({
        facetAddress: ethers.ZeroAddress,
        action: 2, // Remove
        functionSelectors: analysis.toRemove,
      });
    }

    if (analysis.toReplace.length > 0) {
      facetCuts.push({
        facetAddress: facetAddress,
        action: 1, // Replace
        functionSelectors: analysis.toReplace,
      });
    }

    if (analysis.toAdd.length > 0) {
      facetCuts.push({
        facetAddress: facetAddress,
        action: 0, // Add
        functionSelectors: analysis.toAdd,
      });
    }

    // Execute all cuts in a single transaction
    console.log('⚙️  Performing diamondCut with smart selector updates...');
    console.log('   Facet cuts to execute:');
    for (const cut of facetCuts) {
      const actionName =
        cut.action === 0 ? 'Add' : cut.action === 1 ? 'Replace' : 'Remove';
      console.log(
        `   - ${actionName}: ${cut.functionSelectors.length} selectors to ${cut.facetAddress}`,
      );
      cut.functionSelectors.forEach((s) => console.log(`     ${s}`));
    }

    try {
      await executeDiamondCutWithScheduling(
        diamondAddress,
        facetCuts as FacetCutInput[],
      );
    } catch (error: any) {
      console.error('   Diamond cut failed:', error.message);
      // Try executing cuts one at a time to find the problematic one
      console.log('   Attempting individual cuts to identify issue...');
      for (const cut of facetCuts) {
        try {
          const actionName =
            cut.action === 0 ? 'Add' : cut.action === 1 ? 'Replace' : 'Remove';
          console.log(`   Trying ${actionName} cut...`);
          await executeDiamondCutWithScheduling(diamondAddress, [cut]);
          console.log(`   ✓ ${actionName} succeeded`);
        } catch (singleError: any) {
          console.error(
            `   ✗ ${cut.action === 0 ? 'Add' : cut.action === 1 ? 'Replace' : 'Remove'} failed:`,
            singleError.message,
          );
        }
      }
      throw error;
    }

    console.log('   ✓ Diamond cut completed successfully');
    if (analysis.toAdd.length > 0) {
      console.log(`   ✓ Added ${analysis.toAdd.length} new selectors`);
    }
    if (analysis.toReplace.length > 0) {
      console.log(`   ✓ Replaced ${analysis.toReplace.length} selectors`);
    }
    if (analysis.toRemove.length > 0) {
      console.log(`   ✓ Removed ${analysis.toRemove.length} selectors`);
    }
    console.log('');

    // Generate indexer from updated contract ABIs
    if (!dryRun) {
      runIndexerGeneration();
      // Facet upgrades should run the same post-deployment configuration path.
      configAddresses[facetName] = facetAddress;
      await postDeploymentConfig(configAddresses, deployer.address);
    }

    return {
      network: network.name,
      chainId,
      deployer: deployer.address,
      contracts: { [facetName]: { address: facetAddress, blockNumber } },
      timestamp: new Date().toISOString(),
    };
  }

  // Manual action mode (add/replace/remove)
  if (dryRun) {
    console.log(`🔍 DRY RUN - Would ${action} ${selectors.length} selectors\n`);
    return {
      network: network.name,
      chainId: 0,
      deployer: '',
      contracts: {},
      timestamp: new Date().toISOString(),
    };
  }

  const actionCode = action === 'add' ? 0 : action === 'replace' ? 1 : 2;

  console.log(`⚙️  Performing diamondCut (${action})...`);
  await executeDiamondCutWithScheduling(diamondAddress, [
    {
      facetAddress: action === 'remove' ? ethers.ZeroAddress : facetAddress,
      action: actionCode,
      functionSelectors: selectors,
    },
  ]);
  console.log(
    `   ✓ ${action === 'remove' ? 'Removed' : 'Updated'} ${selectors.length} selectors\n`,
  );

  // Facet upgrades should run the same post-deployment configuration path.
  configAddresses[facetName] = facetAddress;
  await postDeploymentConfig(configAddresses, deployer.address);

  return {
    network: network.name,
    chainId,
    deployer: deployer.address,
    contracts:
      action !== 'remove'
        ? { [facetName]: { address: facetAddress, blockNumber } }
        : {},
    timestamp: new Date().toISOString(),
  };
}

// =============================================================================
// MAIN
// =============================================================================

async function main() {
  const args = parseArgs();

  // Handle list commands
  if (args.listModes) {
    printModes();
    return;
  }

  if (args.listContracts) {
    printContracts();
    return;
  }

  // Validate args
  if (!args.mode && !args.contract && !args.facet) {
    console.log('\n❌ No deployment target specified.\n');
    console.log('Usage:');
    console.log('  --mode <name>       Deploy using a predefined mode');
    console.log('  --contract <name>   Deploy a single contract');
    console.log(
      '  --facet <name>      Deploy/update a facet (auto-detects selector changes)',
    );
    console.log(
      '  --action <action>   For facets: auto (default), add, replace, or remove',
    );
    console.log('  --list-modes        List all available deployment modes');
    console.log('  --list-contracts    List all available contracts');
    console.log('  --dry-run           Show what would be deployed');
    console.log('  --skip-config       Skip updating config files\n');
    console.log('Examples:');
    console.log(
      '  DEPLOY_FACET=NodesFacet npx hardhat run scripts/unified-deploy.ts --network baseSepolia',
    );
    console.log('    → Auto-detects which selectors need add/replace/remove\n');
    console.log(
      '  DEPLOY_FACET=CLOBFacet DEPLOY_ACTION=replace npx hardhat run scripts/unified-deploy.ts --network baseSepolia',
    );
    console.log('    → Forces replace of all selectors\n');
    printModes();
    return;
  }

  let deployment: DeploymentResult;

  if (args.facet) {
    // Default to 'auto' if no action specified - smart selector detection
    const action = args.action || 'auto';
    deployment = await updateFacet(args.facet, action, args.dryRun);
  } else if (args.contract) {
    deployment = await deploySingleContract(args.contract, args.dryRun);
  } else if (args.mode) {
    deployment = await deployMode(args.mode, args.dryRun);
  } else {
    throw new Error('Invalid arguments');
  }

  // Skip config updates if dry run or explicitly skipped
  if (args.dryRun || args.skipConfig) {
    console.log('\n⏭️  Skipping config file updates\n');
  } else if (Object.keys(deployment.contracts).length > 0) {
    // Save deployment JSON
    const deploymentsDir = path.resolve('./deployments');
    if (!fs.existsSync(deploymentsDir)) {
      fs.mkdirSync(deploymentsDir, { recursive: true });
    }

    const filename = `${network.name}-${Date.now()}.json`;
    fs.writeFileSync(
      path.join(deploymentsDir, filename),
      JSON.stringify(deployment, null, 2),
    );
    fs.writeFileSync(
      path.join(deploymentsDir, `${network.name}-latest.json`),
      JSON.stringify(deployment, null, 2),
    );
    console.log(`\n📄 Deployment saved to: deployments/${filename}`);

    // Update config files
    console.log('\n📝 Updating configuration files...\n');
    const existingAddresses = loadExistingAddresses();
    updateChainConstants(deployment, existingAddresses);
    updateIndexerConfig(deployment);

    // Regenerate frontend ABI if any facets were deployed
    const deployedFacets = Object.keys(deployment.contracts).filter((name) =>
      name.endsWith('Facet'),
    );
    if (deployedFacets.length > 0) {
      regenerateFrontendABI();
    }
  }

  // Print summary
  console.log('\n' + '='.repeat(60));
  console.log('🎉 DEPLOYMENT COMPLETE!');
  console.log('='.repeat(60));
  console.log(
    `\nNetwork: ${deployment.network} (Chain ID: ${deployment.chainId})`,
  );
  console.log(`Deployer: ${deployment.deployer}`);
  console.log('\nDeployed Contracts:');
  for (const [name, data] of Object.entries(deployment.contracts)) {
    console.log(`  ${name}: ${data.address} (block ${data.blockNumber})`);
  }
  console.log('\n' + '='.repeat(60) + '\n');

  // Run post-deployment verification for facet deployments
  if (
    args.facet &&
    !args.dryRun &&
    Object.keys(deployment.contracts).length > 0
  ) {
    await verifyFacetUpdate(args.facet, deployment);
  }

  // Prompt for git push if not skipped
  if (
    args.facet &&
    !args.dryRun &&
    Object.keys(deployment.contracts).length > 0
  ) {
    await promptGitPush(args.facet);
  }
}

// =============================================================================
// POST-DEPLOYMENT VERIFICATION
// =============================================================================

async function verifyFacetUpdate(
  facetName: string,
  deployment: DeploymentResult,
): Promise<void> {
  console.log('\n🔍 VERIFICATION');
  console.log('='.repeat(60));

  const deployedFacet = deployment.contracts[facetName];
  if (!deployedFacet) {
    console.log('⚠️  No contract deployed, skipping verification');
    return;
  }

  let diamondAddress: string;
  try {
    diamondAddress = await resolveActiveDiamondAddress();
  } catch (error) {
    console.log(
      `⚠️  ${error instanceof Error ? error.message : 'Diamond address not found, skipping on-chain verification'}`,
    );
    return;
  }

  console.log(`Diamond: ${diamondAddress}`);
  console.log(`New ${facetName}: ${deployedFacet.address}`);
  console.log('');

  // Get selectors for this facet
  const selectors = FACET_SELECTORS[facetName];
  if (!selectors || selectors.length === 0) {
    console.log('⚠️  No selectors defined for this facet');
    return;
  }

  // Verify key selectors point to the new facet
  console.log('📋 Verifying selectors...');

  const diamondLoupe = await ethers.getContractAt(
    'IDiamondLoupe',
    diamondAddress,
  );

  let allVerified = true;
  for (const selector of selectors) {
    try {
      const facetAddress = await diamondLoupe.facetAddress(selector);
      const isCorrect =
        facetAddress.toLowerCase() === deployedFacet.address.toLowerCase();

      if (isCorrect) {
        console.log(
          `   ✓ ${selector} → ${facetAddress.slice(0, 6)}...${facetAddress.slice(-4)}`,
        );
      } else {
        console.log(
          `   ✗ ${selector} → ${facetAddress.slice(0, 6)}...${facetAddress.slice(-4)} (WRONG!)`,
        );
        allVerified = false;
      }
    } catch (error: any) {
      console.log(`   ✗ ${selector} → ERROR: ${error.message}`);
      allVerified = false;
    }
  }

  console.log('');
  if (allVerified) {
    console.log('✅ All selectors verified successfully!');
  } else {
    console.log(
      '⚠️  Some selectors did not verify correctly. Check deployment.',
    );
  }

  // Print cast commands for manual verification
  console.log('\n📝 Manual verification commands:');
  console.log('   # Verify specific selector:');
  console.log(
    `   cast call ${diamondAddress} "facetAddress(bytes4)" <selector> --rpc-url <RPC_URL>`,
  );
  console.log('');
  console.log('   # List all facets:');
  console.log(`   cast call ${diamondAddress} "facets()" --rpc-url <RPC_URL>`);
  console.log('');
  console.log('   # Get facet for placeMarketOrder (key function):');
  console.log(
    '   cast call ${diamondAddress} "facetAddress(bytes4)" 0x4c4c96c4 --rpc-url <RPC_URL>',
  );
}

async function promptGitPush(facetName: string): Promise<void> {
  console.log('\n🚀 Git Push to Trigger Indexer Restart');
  console.log('='.repeat(60));
  console.log('To push changes and restart the indexer, run:');
  console.log('');
  console.log('   git add -A');
  console.log(`   git commit -m "feat: Update ${facetName} with fixes"`);
  console.log('   git push origin <branch>');
  console.log('');
  console.log(
    'This will trigger the deployment pipeline and restart the indexer.',
  );
  console.log('');
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error('\n❌ Deployment failed:', error.message);
    process.exit(1);
  });
