export const RWYVaultAbi = [
  // ============ EVENTS ============
  {
    type: 'event',
    name: 'OpportunityCreated',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'operator', type: 'address', indexed: true },
      { name: 'inputToken', type: 'address', indexed: false },
      { name: 'inputTokenId', type: 'uint256', indexed: false },
      { name: 'targetAmount', type: 'uint256', indexed: false },
      { name: 'promisedYieldBps', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommodityStaked',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'staker', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'totalStaked', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CommodityUnstaked',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'staker', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'OpportunityFunded',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'totalAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DeliveryStarted',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'journeyId', type: 'bytes32', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DeliveryConfirmed',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'deliveredAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ProcessingStarted',
    inputs: [{ name: 'opportunityId', type: 'bytes32', indexed: true }],
  },
  {
    type: 'event',
    name: 'ProcessingCompleted',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'outputAmount', type: 'uint256', indexed: false },
      { name: 'outputTokenId', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'SaleOrderCreated',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'clobOrderId', type: 'bytes32', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
      { name: 'price', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'ProfitDistributed',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'staker', type: 'address', indexed: true },
      { name: 'principal', type: 'uint256', indexed: false },
      { name: 'profit', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'OpportunityCancelled',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'reason', type: 'string', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'OperatorSlashed',
    inputs: [
      { name: 'opportunityId', type: 'bytes32', indexed: true },
      { name: 'operator', type: 'address', indexed: true },
      { name: 'slashedAmount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'OperatorApproved',
    inputs: [{ name: 'operator', type: 'address', indexed: true }],
  },
  {
    type: 'event',
    name: 'OperatorRevoked',
    inputs: [{ name: 'operator', type: 'address', indexed: true }],
  },

  // ============ READ FUNCTIONS ============
  {
    type: 'function',
    name: 'getOpportunity',
    stateMutability: 'view',
    inputs: [{ name: 'opportunityId', type: 'bytes32' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'id', type: 'bytes32' },
          { name: 'operator', type: 'address' },
          { name: 'name', type: 'string' },
          { name: 'description', type: 'string' },
          { name: 'inputToken', type: 'address' },
          { name: 'inputTokenId', type: 'uint256' },
          { name: 'targetAmount', type: 'uint256' },
          { name: 'stakedAmount', type: 'uint256' },
          { name: 'outputToken', type: 'address' },
          { name: 'outputTokenId', type: 'uint256' },
          { name: 'expectedOutputAmount', type: 'uint256' },
          { name: 'promisedYieldBps', type: 'uint256' },
          { name: 'operatorFeeBps', type: 'uint256' },
          { name: 'minSalePrice', type: 'uint256' },
          { name: 'fundingDeadline', type: 'uint256' },
          { name: 'processingDeadline', type: 'uint256' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'fundedAt', type: 'uint256' },
          { name: 'completedAt', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'operatorCollateral', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getStake',
    stateMutability: 'view',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'staker', type: 'address' },
    ],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'amount', type: 'uint256' },
          { name: 'stakedAt', type: 'uint256' },
          { name: 'claimed', type: 'bool' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getOpportunityStakers',
    stateMutability: 'view',
    inputs: [{ name: 'opportunityId', type: 'bytes32' }],
    outputs: [{ type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'getOpportunityCount',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'getAllOpportunities',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bytes32[]' }],
  },
  {
    type: 'function',
    name: 'isApprovedOperator',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getOperatorStats',
    stateMutability: 'view',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [
      { name: 'approved', type: 'bool' },
      { name: 'reputation', type: 'uint256' },
      { name: 'successfulOps', type: 'uint256' },
      { name: 'totalValueProcessed', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'calculateExpectedProfit',
    stateMutability: 'view',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'stakeAmount', type: 'uint256' },
    ],
    outputs: [
      { name: 'expectedProfit', type: 'uint256' },
      { name: 'userShareBps', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'approvedOperators',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'operatorReputation',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'operatorSuccessfulOps',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'operatorTotalValueProcessed',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'saleProceeds',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'bytes32' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'proceedsFinalized',
    stateMutability: 'view',
    inputs: [{ name: '', type: 'bytes32' }],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'minOperatorCollateralBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'maxYieldBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'protocolFeeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'feeRecipient',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'clobAddress',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'quoteToken',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },

  // ============ WRITE FUNCTIONS ============
  {
    type: 'function',
    name: 'createOpportunity',
    stateMutability: 'payable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'description', type: 'string' },
      { name: 'inputToken', type: 'address' },
      { name: 'inputTokenId', type: 'uint256' },
      { name: 'targetAmount', type: 'uint256' },
      { name: 'outputToken', type: 'address' },
      { name: 'expectedOutputAmount', type: 'uint256' },
      { name: 'promisedYieldBps', type: 'uint256' },
      { name: 'operatorFeeBps', type: 'uint256' },
      { name: 'minSalePrice', type: 'uint256' },
      { name: 'fundingDays', type: 'uint256' },
      { name: 'processingDays', type: 'uint256' },
    ],
    outputs: [{ type: 'bytes32' }],
  },
  {
    type: 'function',
    name: 'stake',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unstake',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'startDelivery',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'journeyId', type: 'bytes32' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'confirmDelivery',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'deliveredAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'completeProcessing',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'outputTokenId', type: 'uint256' },
      { name: 'actualOutputAmount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'recordSaleProceeds',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'proceeds', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'claimProfits',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'opportunityId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'emergencyClaim',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'opportunityId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelOpportunity',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'reason', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'approveOperator',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'revokeOperator',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'operator', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setMinCollateralBps',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bps', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setMaxYieldBps',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bps', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setProtocolFeeBps',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'bps', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setCLOBAddress',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_clob', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setQuoteToken',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_quoteToken', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setFeeRecipient',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_feeRecipient', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setDefaultProcessingDays',
    stateMutability: 'nonpayable',
    inputs: [{ name: '_days', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'slashOperator',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'forceCancel',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'opportunityId', type: 'bytes32' },
      { name: 'reason', type: 'string' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'unpause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
] as const;
